### ISSUE TITLE
frdm_k64f/samples/net/gptp/test: irq line 85 registered twice

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#11275]
As noted in build failures for #11273 which checks for this.
IRQ_CONNECT() shouldn't ever be called more than once on the same IRQ line, it's undefined which one will actually get registered.

```
[167/170] Generating isr_tables.c
FAILED: cd /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/out-2nd-pass/frdm_k64f/samples/net/gptp/test/zephyr && /opt/sdk/zephyr-sdk-0.9.5/sysroots/x86_64-pokysdk-linux/usr/bin/arm-zephyr-eabi/arm-zephyr-eabi-objcopy -I elf32-littlearm -O binary --only-section=.intList /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/out-2nd-pass/frdm_k64f/samples/net/gptp/test/zephyr/zephyr_prebuilt.elf isrList.bin && /usr/bin/python3 /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py --output-source isr_tables.c --kernel /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/out-2nd-pass/frdm_k64f/samples/net/gptp/test/zephyr/zephyr_prebuilt.elf --intlist isrList.bin   --sw-isr-table --vector-table
gen_isr_tables.py: multiple registrations for irq 85 (0x55)
Traceback (most recent call last):
  File "/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py", line 295, in <module>
    main()
  File "/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py", line 287, in main
    error("multiple registrations for irq %d (0x%x)" % (irq, irq))
  File "/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py", line 34, in error
    raise Exception()
Exception
ninja: build stopped: subcommand failed.
```

**Comment by jukkar** [comment]
This crash is most probably related. I am seeing this message from samples/net/gptp when running the app in frdm_k64f
```
***** Spurious interrupt (IRQ  82) *****
***** Hardware exception *****
Current thread ID = 0x20001f98
Faulting instruction address = 0xa10a
Fatal fault in ISR! Spinning...
```
