### ISSUE TITLE
Accurate error message when attempting to build using west with uncompatible cmake version

### ISSUE THREAD

**Issue by martinpalsson** [zephyrproject-rtos/zephyr#17020]
**Is your enhancement proposal related to a problem? Please describe.**
When attempting to build with west on a pc where an old version of cmake is present, it is possible that west runs with the old version of cmake leading to a build error with inaccurate error message.

**Describe the solution you'd like**
Add an help string when cmake returns an error code,
`Please check your cmake version with cmake --version`

**Describe alternatives you've considered**
A check for cmake version right after shutil.which in zcmake.py run_cmake

**Additional context**
Example of output when west runs with an old version of cmake:
`[martin@localhost zephyr]$ west -v build -b sam_e70_xplained samples/hello_world

ZEPHYR_BASE=/home/martin/Dev/zep/zprj2/zephyr (origin: env)

source directory: /home/martin/Dev/zep/zprj2/zephyr/samples/hello_world

build directory: /home/martin/Dev/zep/zprj2/zephyr/build

BOARD: sam_e70_xplained (origin: command line)

Running CMake: /usr/local/bin/cmake -B/home/martin/Dev/zep/zprj2/zephyr/build -S/home/martin/Dev/zep/zprj2/zephyr/samples/hello_world -GNinja -DBOARD=sam_e70_xplained

CMake Error: The source directory "" does not exist.

Specify --help for usage, or press the help button on the CMake GUI.

ERROR: command exited with status 1: /usr/local/bin/cmake -B/home/martin/Dev/zep/zprj2/zephyr/build -S/home/martin/Dev/zep/zprj2/zephyr/samples/hello_world -GNinja -DBOARD=sam_e70_xplained

Traceback (most recent call last):

  File "/home/martin/Dev/zep/zprj2/.west/west/src/west/main.py", line 580, in main

    args.handler(args, unknown)

  File "/home/martin/Dev/zep/zprj2/.west/west/src/west/main.py", line 332, in ext_command_handler

    command.run(*west_parser.parse_known_args(argv))

  File "/home/martin/Dev/zep/zprj2/.west/west/src/west/commands/command.py", line 90, in run

    self.do_run(args, unknown)

  File "/home/martin/Dev/zep/zprj2/zephyr/scripts/west_commands/build.py", line 164, in do_run

    self._run_cmake(board, origin, self.args.cmake_opts)

  File "/home/martin/Dev/zep/zprj2/zephyr/scripts/west_commands/build.py", line 394, in _run_cmake

    run_cmake(final_cmake_args, dry_run=self.args.dry_run)

  File "/home/martin/Dev/zep/zprj2/zephyr/scripts/west_commands/zcmake.py", line 68, in run_cmake

    raise subprocess.CalledProcessError(p.returncode, p.args)

subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '-B/home/martin/Dev/zep/zprj2/zephyr/build', '-S/home/martin/Dev/zep/zprj2/zephyr/samples/hello_world', '-GNinja', '-DBOARD=sam_e70_xplained']' returned non-zero exit status 1.`

**Comment by pdgendt** [comment]
@martinpalsson could you verify if this still an issue? AFAICS the `cmake` error is

```
CMake Error: The source directory "" does not exist.
```

Almost all samples/tests currently have:

```cmake
cmake_minimum_required(VERSION 3.20.0)
```

Which, I would assume, should result in a different error message.
