### ISSUE TITLE
net: IPv4/UDP datagram with zero src addr and TTL causes Zephyr to segfault

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#17427]
If Zephyr echo server receives IPv4/UDP datagram with source IP address and TTL set to zero it seems to quit with log (89=EDESTADDRREQ?):

```
[00:00:23.340,000] <err> net_echo_server_sample: UDP (IPv4): Failed to send 89
[00:00:23.340,000] <inf> net_echo_server_sample: Stopping...
```
If after that IPv6/TCP packet is sent to Zephyr it causes segmentation fault with backtrace:

```
#0  sys_dlist_remove (node=0xf30fa1bc) at dlist.h:524
#1  sys_dlist_get (list=0x56589edc <contexts+124>) at dlist.h:544
#2  z_handle_obj_poll_events (events=0x56589edc <contexts+124>, state=4) at poll.c:377
#3  0x5657602e in handle_poll_events (state=4, queue=0x56589ed4 <contexts+116>) at queue.c:176
#4  queue_insert (queue=0x56589ed4 <contexts+116>, prev=0x0, data=<optimized out>, alloc=false) at queue.c:176
#5  0x565744d7 in _tcp_syn_rcvd (conn=<optimized out>, proto_hdr=<optimized out>, user_data=<optimized out>, ip_hdr=<optimized out>, pkt=<optimized out>) at tcp.c:2442
#6  tcp_syn_rcvd (conn=<optimized out>, pkt=<optimized out>, ip_hdr=<optimized out>, proto_hdr=<optimized out>, user_data=<optimized out>) at tcp.c:2247
#7  0x56572560 in net_conn_input (pkt=0x56586bd8 <_k_mem_slab_buf_rx_pkts+1080>, ip_hdr=0xf40fc248, proto=6 '\006', proto_hdr=0xf40fc244) at connection.c:616
#8  0x5656cb11 in net_ipv6_input (pkt=0x56586bd8 <_k_mem_slab_buf_rx_pkts+1080>, is_loopback=false) at ipv6.c:540
#9  0x565675ca in process_data (pkt=pkt@entry=0x56586bd8 <_k_mem_slab_buf_rx_pkts+1080>, is_loopback=<optimized out>) at net_core.c:127
#10 0x56567629 in processing_data (is_loopback=false, pkt=0x56586bd8 <_k_mem_slab_buf_rx_pkts+1080>) at net_core.c:354
#11 net_rx (pkt=0x56586bd8 <_k_mem_slab_buf_rx_pkts+1080>, iface=<optimized out>) at net_core.c:354
#12 process_rx_packet (work=0x56586bd8 <_k_mem_slab_buf_rx_pkts+1080>) at net_core.c:366
#13 0x5655d630 in z_work_q_main (work_q_ptr=0x5658a6a0 <rx_classes>, p2=0x0, p3=0x0) at work_q.c:32
#14 0x5655d5cf in z_thread_entry (entry=0x5655d5f7 <z_work_q_main>, p1=0x5658a6a0 <rx_classes>, p2=0x0, p3=0x0) at thread_entry.c:29
#15 0x565633d0 in posix_thread_starter (arg=0x565871e4 <rx_stack+1476>) at posix_core.c:301
#16 0xf7e68fd2 in start_thread (arg=<optimized out>) at pthread_create.c:486
#17 0xf7d7e6d6 in clone () at clone.S:108
```

Three pcaps attached:
ipv4-udp-zero-src-ttl.pcap.gz - IPv4/UDP packet with zero source IP address and TTL
ipv6-tcp.pcap.gz - IPv6/TCP packet that causes segfault
replay.pcap.gz - compbination of packets from ipv4-udp-zero-src-ttl.pcap.gz and ipv6-tcp.pcap.gz. Can be used to reproduce segfault with tcpreplay

[ipv4-udp-zero-src-ttl.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3373326/ipv4-udp-zero-src-ttl.pcap.gz)
[ipv6-tcp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3373327/ipv6-tcp.pcap.gz)
[replay.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3373328/replay.pcap.gz)

**Comment by rmstoi** [comment]
with PR #17428 Zephyr does not crash and udp packet is correctly dropped

```
[00:00:19.740,000] <dbg> net_ipv4.net_ipv4_input: (0x5658c6b0): DROP: src addr is unspecified
[00:00:37.560,000] <inf> net_echo_server_sample: TCP (IPv6): Accepted connection
[00:00:37.620,000] <dbg> net_echo_server_sample.process_tcp: TCP (IPv6): Received and replied with 640 bytes
[00:00:37.680,000] <dbg> net_echo_server_sample.process_tcp: TCP (IPv6): Received and replied with 360 bytes
[00:00:39.350,000] <inf> net_echo_server_sample: TCP (IPv6): Connection closed
[00:00:39.350,000] <inf> net_echo_server_sample: Waiting for TCP connection on port 4242 (IPv6)...
```
