### ISSUE TITLE
missing or empty reg/ranges property when trying to build blink_led example

### ISSUE THREAD

**Issue by luigiluz** [zephyrproject-rtos/zephyr#19833]
When I try to build any application, it shows this error followed by KeyError: '#cells' and it doesn't finish the build.

I've tried to search something related to this problem but I couldn't find anything that could help.

I only used the command: west build -b nrf52840_pca10056

```
west build -b nrf52840_pca10056
source directory: /home/luigifernandomarquesdaluz/zephyr/samples/basic/blink_led
build directory: /home/luigifernandomarquesdaluz/zephyr/samples/basic/blink_led/build (created)
BOARD: nrf52840_pca10056
Zephyr version: 1.14.1
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.8", minimum required is "3.4") 
-- Selected BOARD nrf52840_pca10056
-- Found west: /home/luigifernandomarquesdaluz/.local/bin/west (found suitable version "0.6.2", minimum required is "0.5.6")
-- Loading /home/luigifernandomarquesdaluz/zephyrproject/zephyr/boards/arm/nrf52840_pca10056/nrf52840_pca10056.dts as base
-- Overlaying /home/luigifernandomarquesdaluz/zephyrproject/zephyr/dts/common/common.dts
nrf52840_pca10056.dts.pre.tmp:317.23-320.5: Warning (simple_bus_reg): /soc/virtualcom: missing or empty reg/ranges property
Traceback (most recent call last):
  File "/home/luigifernandomarquesdaluz/zephyrproject/zephyr/scripts/dts/extract_dts_includes.py", line 517, in <module>
    main()
  File "/home/luigifernandomarquesdaluz/zephyrproject/zephyr/scripts/dts/extract_dts_includes.py", line 503, in main
    generate_defines()
  File "/home/luigifernandomarquesdaluz/zephyrproject/zephyr/scripts/dts/extract_dts_includes.py", line 446, in generate_defines
    generate_node_defines(node_path)
  File "/home/luigifernandomarquesdaluz/zephyrproject/zephyr/scripts/dts/extract_dts_includes.py", line 126, in generate_node_defines
    generate_prop_defines(node_path, prop)
  File "/home/luigifernandomarquesdaluz/zephyrproject/zephyr/scripts/dts/extract_dts_includes.py", line 91, in generate_prop_defines
    names, 0, def_label, generic)
  File "/home/luigifernandomarquesdaluz/zephyrproject/zephyr/scripts/dts/extract/globals.py", line 455, in extract_cells
    l_cellname = [str(cell_yaml[cell_yaml_names][j]).upper()]
KeyError: '#cells'
CMake Error at /home/luigifernandomarquesdaluz/zephyrproject/zephyr/cmake/dts.cmake:174 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/luigifernandomarquesdaluz/zephyrproject/zephyr/cmake/app/boilerplate.cmake:399 (include)
  CMakeLists.txt:4 (include)


-- Configuring incomplete, errors occurred!
ERROR: command exited with status 1: /home/luigifernandomarquesdaluz/bin/cmake/cmake-3.13.1-Linux-x86_64/bin/cmake -B/home/luigifernandomarquesdaluz/zephyr/samples/basic/blink_led/build -S/home/luigifernandomarquesdaluz/zephyr/samples/basic/blink_led -GNinja -DBOARD=nrf52840_pca10056
```

**Comment by carlescufi** [comment]
This builds fine on my machine, can you try the following:

- Remove any build folders completely
- Make sure you have run `west update`

**Comment by luigiluz** [comment]
> This builds fine on my machine, can you try the following:
> 
>     * Remove any build folders completely
> 
>     * Make sure you have run `west update`

I've just tried doing this, but the error remains the same :/

**Comment by ulfalizer** [comment]
Not sure what's going on here either. Works for me when running `cmake -GNinja -DBOARD=nrf52840_pca10056 ..` in `samples/basic/blink_led/b`.

From the error it looks like a missing `*-cells:` key in a binding (`.yaml` file), e.g. `gpio-cells:`. Could you try applying this patch and seeing what the last node path it prints before the error is?

The problem might be with the binding for that node.

```diff
diff --git a/scripts/dts/extract/globals.py b/scripts/dts/extract/globals.py
index 86db6411bc..60e2665d75 100644
--- a/scripts/dts/extract/globals.py
+++ b/scripts/dts/extract/globals.py
@@ -535,6 +535,8 @@ def extract_cells(node_path, prop, prop_values, names, index,
         except Exception:
             name = ''
 
+        print("cell parent: " + cell_parent, flush=True)
+
         # Get number of cells per element of current property
         for props in reduced[cell_parent]['props']:
             if props[0] == '#' and '-cells' in props:
```

**Comment by carlescufi** [comment]
@luigiluz are you sure you are on the latest master and with no local changes?

**Comment by carlescufi** [comment]
ah wait, you are on 1.14.1? @ulfalizer that might explain it.

**Comment by luigiluz** [comment]
maybe i've messed up and cloned an outdated master
 i'll only be able to apply this suggestions tomorrow, but i'll update my situation here as soon as I can

**Comment by carlescufi** [comment]
> maybe i've messed up and cloned an outdated master
> i'll only be able to apply this suggestions tomorrow, but i'll update my situation here as soon as I can

I think you have a very old master, from the build output:
>Zephyr version: 1.14.1

**Comment by luigiluz** [comment]
i've updated to version 2.0.99 and it worked properly, thanks guys
