### ISSUE TITLE
devicetree: fix non-deterministic multi-level interrupt encodings

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#20571]
The scripting that generates multi-level IRQ information does not guarantee determininstic instance order.  While it can be patched by hard-coding specific instances as with #20550 and #20562 the problem needs to be solved more generally.

Example output from #20558.

**Screenshots or console output**
```
[184/188] Generating linker_pass_final.cmd
[185/188] Generating isr_tables.c
FAILED: cd /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/rv32m1_vega_ri5cy/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr_rv32m1_vega_ri5cy/zephyr && /opt/sdk/zephyr-sdk-0.10.3/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-objcopy --input-target=elf32-littleriscv --output-target=binary --only-section=.intList /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/rv32m1_vega_ri5cy/samples/bluetooth/peripheral_hr/sample.bluetoot.h.peripheral_hr_rv32m1_vega_ri5cy/zephyr/zephyr_prebuilt.elf isrList.bin && /usr/bin/python3 /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py --output-source isr_tables.c --kernel /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/rv32m1_vega_ri5cy/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr_rv32m1_vega_ri5cy/zephyr/zephyr_prebuilt.elf --intlist isrList.bin   --sw-isr-table
gen_isr_tables.py: multiple registrations at table_index 25 for irq 25 (0x19)
Traceback (most recent call last):
  File "/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py", line 314, in <module>
    main()
  File "/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py", line 306, in main
    error("multiple registrations at table_index %d for irq %d (0x%x)" % (table_index, irq, irq))
  File "/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/common/gen_isr_tables.py", line 36, in error
    raise Exception()
Exception
ninja: build stopped: subcommand failed.
```

**Comment by carlescufi** [comment]
Setting priority to high because this completely defeats the deterministic nature of DT.

**Comment by ulfalizer** [comment]
Didn't notice this one until now, but I wonder if https://github.com/zephyrproject-rtos/zephyr/pull/20597 solves it. In that case it was only an issue on Python 3.5 and earlier. CI runs 3.5.
