### ISSUE TITLE
mimxrt1020_evk: total freeze

### ISSUE THREAD

**Issue by dieselburner** [zephyrproject-rtos/zephyr#24612]
**Describe the bug**

It looks like `mimxrt1020_evk` is broken. Building/flashing works as expected. However, running any sample application gives no output on UART or any other peripheral.

**To Reproduce**

1. `west build -p auto -b mimxrt1020_evk samples/hello_world`
2. `west flash`
3. No output at all

**Expected behavior**

Text `Hello World! mimxrt1020_evk` on UART console.

**Impact**

Showstopper for imxrt1020 based boards and possibly for other iMX RT targets.

**Screenshots or console output**

```
andrejs@ubuntu-vm-nm:~/source/zephyr/zephyr$ west debug
-- west debug: rebuilding
ninja: no work to do.
-- west debug: using runner jlink
-- runners.jlink: J-Link GDB server running on port 2331
SEGGER J-Link GDB Server V6.62d Command Line Version
JLinkARM.dll V6.62d (DLL compiled Mar  2 2020 09:23:31)
-----GDB Server start settings-----
GDBInit file:                  none
GDB Server Listening port:     2331
SWO raw output listening port: 2332
Terminal I/O port:             2333
Accept remote connection:      yes
Generate logfile:              off
Verify download:               off
Init regs on start:            off
Silent mode:                   on
Single run mode:               on
Target connection timeout:     0 ms
------J-Link related settings------
J-Link Host interface:         USB
J-Link script:                 none
J-Link settings file:          none
------Target related settings------
Target device:                 MIMXRT1021xxx5A
Target interface:              SWD
Target interface speed:        auto
Target endian:                 little
GNU gdb (crosstool-NG 1.24.0.37-3f461da-dirty) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=arm-zephyr-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/andrejs/source/zephyr/zephyr/build/zephyr/zephyr.elf...
Remote debugging using :2331
0x600051de in _sw_isr_table ()
Resetting target
Loading section rom_start, size 0x2278 lma 0x60000000
Loading section text, size 0x2c34 lma 0x60002278
Loading section .ARM.exidx, size 0x8 lma 0x60004eac
Loading section sw_isr_table, size 0x470 lma 0x60004eb4
Loading section devconfig, size 0xa8 lma 0x60005324
Loading section rodata, size 0x1f0 lma 0x600053cc
Loading section datas, size 0x13 lma 0x600055bc
Loading section initlevel, size 0xa8 lma 0x600055d0
Loading section _k_mutex_area, size 0x14 lma 0x60005678
Start address 0x600037fc, load size 22155
Transfer rate: 7211 KB/sec, 2461 bytes/write.
(gdb) b main
Breakpoint 1 at 0x60002570: file /home/andrejs/source/zephyr/zephyr/samples/hello_world/src/main.c, line 12.
(gdb) c
Continuing.
^C
Program received signal SIGTRAP, Trace/breakpoint trap.
0x600036b4 in __NVIC_EnableIRQ (IRQn=GPIO5_Combined_0_15_IRQn) at /home/andrejs/source/zephyr/modules/hal/cmsis/CMSIS/Core/Include/core_cm7.h:1912
1912	    NVIC->ISER[(((uint32_t)IRQn) >> 5UL)] = (uint32_t)(1UL << (((uint32_t)IRQn) & 0x1FUL));
(gdb) bt
#0  __NVIC_EnableIRQ (IRQn=GPIO5_Combined_0_15_IRQn) at /home/andrejs/source/zephyr/modules/hal/cmsis/CMSIS/Core/Include/core_cm7.h:1912
#1  arch_irq_enable (irq=irq@entry=88) at /home/andrejs/source/zephyr/zephyr/arch/arm/core/aarch32/irq_manage.c:40
#2  0x60004c06 in mcux_igpio_4_init (dev=<optimized out>) at /home/andrejs/source/zephyr/zephyr/drivers/gpio/gpio_mcux_igpio.c:267
#3  0x60003d56 in z_sys_device_do_config_level (level=level@entry=2) at /home/andrejs/source/zephyr/zephyr/kernel/device.c:60
#4  0x60003e06 in bg_thread_main (unused1=<optimized out>, unused2=<optimized out>, unused3=<optimized out>) at /home/andrejs/source/zephyr/zephyr/kernel/init.c:217
#5  0x60004676 in z_thread_entry (entry=0x60003df9 <bg_thread_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/andrejs/source/zephyr/zephyr/lib/os/thread_entry.c:29
#6  0x6000375a in arch_switch_to_main_thread (main_thread=0x800000e8 <z_main_thread>, main_stack=<optimized out>, main_stack_size=1024, _main=0x60003df9 <bg_thread_main>)
    at /home/andrejs/source/zephyr/zephyr/arch/arm/core/aarch32/thread.c:434
#7  0x0f0f0f0e in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Environment (please complete the following information):**

 - OS: Ubuntu 18.04.4 LTS
 - Toolchain: Zephyr SDK v0.11.2
 - Commit SHA or Version used: e737761d23c00172b76af4821b63edfd0bbc0df3

**Additional context**

Works in v2.2.0

**Comment by dieselburner** [comment]
Duplicate of #24579. Fixed in #24606.
