### ISSUE TITLE
"west zephyr-export" dumps stack if cmake is not installed

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#27375]
**Describe the bug**
The `west zephyr-export` command should fail gracefully if cmake is not installed, but it does not

**To Reproduce**
1. uninstall cmake
2. make sure no cmake user package entries exist for zephyr (maybe; optional -- that's how I tested)
3. `west zephyr-export`

Output:

```
$ west zephyr-export
FATAL ERROR: CMake is not installed or cannot be found; cannot build.
Traceback (most recent call last):
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/export.py", line 59, in run_cmake_and_clean_up
    lines = run_cmake(['-S', str(path), '-B', str(path)],
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/zcmake.py", line 44, in run_cmake
    log.die('CMake is not installed or cannot be found; cannot build.')
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/log.py", line 146, in die
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbolivar/.virtualenvs/west-test/bin/west", line 8, in <module>
    sys.exit(main())
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 780, in main
    app.run(argv or sys.argv[1:])
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 339, in run_command
    self.run_extension(args.command, argv)
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 409, in run_extension
    command.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/commands.py", line 116, in run
    self.do_run(args, unknown)
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/export.py", line 48, in do_run
    run_cmake_and_clean_up(share / 'zephyr-package' / 'cmake')
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/export.py", line 62, in run_cmake_and_clean_up
    msg = [line for line in lines if not line.startswith('-- ')]
```

**Expected behavior**

No stack dump, just a clean error message

**Impact**

Annoyance

**Environment (please complete the following information):**

 - Commit SHA or Version used: d5e1753eb6c36421a87b535e8e6cb3a9d50e06e4

**Comment by tejlmand** [comment]
Thanks for raising this.
It actually gave me the opportunity to cleanup Zephyr export, something I have wanted to do for some time, but as things were working, I found no reason.

Fixed now.
