### ISSUE TITLE
tests: net: socket: af_packet: failed on nucleo_f746zg

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#27963]
**Describe the bug**
Tests tests/net/socket/af_packet fails on nucleo_f746zg.
It used to be passed previously, so I run git bisect and found that 

> sha1:1a01aacd166bd393c4bbe80171ff74368a48970c

cause the regression.
Note: this test runs on test bench and there is no ethernet cable connected.

Thanks to debugger I found that I end up in `return NULL;` of function `z_impl_k_queue_get()`
```
	if (K_TIMEOUT_EQ(timeout, K_NO_WAIT)) {
		k_spin_unlock(&queue->lock, key);
		return NULL;
	}
```

The backtrace at this point is:
```
#0  z_impl_k_queue_get (queue=queue@entry=0x2001ac8c <tx_bufs>, timeout=...) at C:/zephyr/zephyr_project/zephyr/kernel/queue.c:293
#1  0x0800694e in k_queue_get (timeout=..., queue=0x2001ac8c <tx_bufs>) at zephyr/include/generated/syscalls/kernel.h:579
#2  net_buf_alloc_len (pool=pool@entry=0x2001ac8c <tx_bufs>, size=<optimized out>, timeout=...) at C:/zephyr/zephyr_project/zephyr/subsys/net/buf.c:261
#3  0x08019d90 in net_buf_alloc_fixed (pool=pool@entry=0x2001ac8c <tx_bufs>, timeout=...) at C:/zephyr/zephyr_project/zephyr/subsys/net/buf.c:371
#4  0x0801b442 in net_pkt_get_reserve_data (pool=pool@entry=0x2001ac8c <tx_bufs>, timeout=...) at C:/zephyr/zephyr_project/zephyr/subsys/net/ip/net_pkt.c:381
#5  0x0800a6d0 in net_pkt_get_reserve_tx_data (timeout=...) at C:/zephyr/zephyr_project/zephyr/subsys/net/ip/net_pkt.c:467
#6  0x0800a6ea in net_pkt_get_frag (pkt=pkt@entry=0x20013f18 <_k_mem_slab_buf_tx_pkts+1944>, timeout=...) at C:/zephyr/zephyr_project/zephyr/subsys/net/ip/net_pkt.c:441
#7  0x08019df4 in ethernet_fill_header (ctx=ctx@entry=0x20010698 <_net_l2_data_eth_fake10>, pkt=pkt@entry=0x20013f18 <_k_mem_slab_buf_tx_pkts+1944>, ptype=0) at ../include/sys/time_units.h:371
#8  0x08006c78 in ethernet_send (iface=0x2001acc0 <__net_if_eth_fake1_0>, pkt=0x20013f18 <_k_mem_slab_buf_tx_pkts+1944>) at C:/zephyr/zephyr_project/zephyr/subsys/net/l2/ethernet/ethernet.c:654
#9  0x080082d6 in net_if_tx (iface=0x2001acc0 <__net_if_eth_fake1_0>, pkt=0x20013f18 <_k_mem_slab_buf_tx_pkts+1944>) at ../include/net/net_if.h:558
#10 0x0801aa38 in process_tx_packet (work=<optimized out>) at C:/zephyr/zephyr_project/zephyr/subsys/net/ip/net_if.c:358
#11 0x080016f8 in z_work_q_main (work_q_ptr=0x20010228 <tx_classes>, p2=<optimized out>, p3=<optimized out>) at C:/zephyr/zephyr_project/zephyr/lib/os/work_q.c:33
#12 0x08018980 in z_thread_entry (entry=0x8001675 <z_work_q_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at C:/zephyr/zephyr_project/zephyr/lib/os/thread_entry.c:29
#13 0x08018980 in z_thread_entry (entry=0x8001675 <z_work_q_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at C:/zephyr/zephyr_project/zephyr/lib/os/thread_entry.c:29
```

**To Reproduce**
1. west build -p auto -b nucleo_f746zg tests/net/socket/af_packet
2. west flash
3. See error

**Expected behavior**
Tests passed

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.3.0-2168-g0bac13660414  ***
Running test suite socket_packet
===================================================================
START - test_packet_sockets
 PASS - test_packet_sockets
===================================================================
START - test_packet_sockets_dgram

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:225: test_packet_sockets_dgram: (ret not equal to sizeof(data_to_send))
Cannot receive all data (-1 vs 10) (-11)
 FAIL - test_packet_sockets_dgram
===================================================================
Test suite socket_packet failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux and Windows)
 - Toolchain Zephyr SDK
 - Commit SHA:2ce87da252da7edca436046eede433a2ff380f27

**Comment by ABOSTM** [comment]
Note: the same on nucleo_f429zi
