### ISSUE TITLE
SNTP doesn't work on v2.4.0 on eswifi

### ISSUE THREAD

**Issue by micholek** [zephyrproject-rtos/zephyr#29826]
**Describe the bug**
Calling `sntp_simple()` results in error:

```
[00:00:08.670,000] <err> net_sntp: Error in poll:116
```

**To Reproduce**
Use the following code on `disco_l475_iot1`, compile with `west` (`west build -b disco_l475_iot1 .`):

```
struct sntp_time time;
const uint32_t timeout_ms = 5000;
if (sntp_simple("time.nist.gov", timeout_ms, &time)) {
    printf("Failed to get current time");
}
```

**Expected behavior**
`time` should be set to the current timestamp.

**Impact**
The bug forces the application to use older version of zephyr (v2.3.0).

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version: v2.4.0

**Additional context**
I think the problem originates somewhere from `eswifi_socket_ioctl` function:

```
#0  eswifi_socket_ioctl (obj=0x2, request=260, args=...) at /home/michal/zephyrproject/zephyr/drivers/wifi/eswifi/eswifi_socket_offload.c:522
#1  0x08047128 in z_fdtable_call_ioctl (vtable=vtable@entry=0x805bbb8 <eswifi_socket_fd_op_vtable>, obj=obj@entry=0x2, request=260) at /home/michal/zephyrproject/zephyr/include/sys/fdtable.h:123
#2  0x08007786 in z_impl_zsock_poll (fds=fds@entry=0x20009a24 <z_main_stack+15916>, nfds=1, poll_timeout=poll_timeout@entry=400) at /home/michal/zephyrproject/zephyr/subsys/net/lib/sockets/sockets.c:1325
#3  0x08001c1e in zsock_poll (timeout=400, nfds=<optimized out>, fds=0x20009a24 <z_main_stack+15916>) at zephyr/include/generated/syscalls/socket.h:202
#4  poll (timeout=400, nfds=<optimized out>, fds=0x20009a24 <z_main_stack+15916>) at /home/michal/zephyrproject/zephyr/include/posix/poll.h:25
#5  sntp_recv_response (time=0x20009a58 <z_main_stack+15968>, timeout=400, sntp=0x20009a24 <z_main_stack+15916>) at /home/michal/zephyrproject/zephyr/subsys/net/lib/sntp/sntp.c:109
#6  sntp_query (ctx=ctx@entry=0x20009a24 <z_main_stack+15916>, timeout=timeout@entry=400, time=time@entry=0x20009a58 <z_main_stack+15968>) at /home/michal/zephyrproject/zephyr/subsys/net/lib/sntp/sntp.c:205
#7  0x080072f8 in sntp_simple (server=server@entry=0x8060110 "time.nist.gov", timeout=timeout@entry=5000, time=time@entry=0x20009a58 <z_main_stack+15968>) at /home/michal/zephyrproject/zephyr/subsys/net/lib/sntp/sntp_simple.c:49
```

**Comment by nandojve** [comment]
CC: @erwango
