### ISSUE TITLE
updatehub with openthread build update pkg failed

### ISSUE THREAD

**Issue by IHIDCHAOS** [zephyrproject-rtos/zephyr#30999]
**Describe the bug**
Hello
I am trying to follow this issue #30316 and zephyr [doc](https://docs.zephyrproject.org/latest/samples/subsys/mgmt/updatehub/README.html) to do an update for my nrf52840dk using updatehub with openthread. 

And the updatehub runs successfully:
```
uart:~$ updatehub run
Starting UpdateHub run...
No update found
```
But I ran into some problems while creating the upgrade package.

**To Reproduce**
```
cd ~/zephyrproject/

west build -b nrf52840dk_nrf52840 -s bootloader/mcuboot/boot/zephyr -d build-mcuboot

west flash -d build-mcuboot

west build -b nrf52840dk_nrf52840 -d build/app zephyr/samples/subsys/mgmt/updatehub -- -DOVERLAY_CONFIG="overlay-ot.conf;overlay-prj.conf"

west sign -t imgtool -d build/app -- --version 1.0.0 --pad --key bootloader/mcuboot/root-rsa-2048.pem

**here I use hex file because it seems bin file failed to startup on my board.**
west flash -d build/app --hex-file build/app/zephyr/zephyr.signed.hex

west sign --no-hex --bin -B build/zephyr-2.0.0.bin -t imgtool -d build/app -- --version 2.0.0 --key bootloader/mcuboot/root-rsa-2048.pem

uhu product use "e4d37cfe6ec48a2d069cc0bbb8b078677e9a0d8df3a027c4d8ea131130c4265f"

uhu package add build/zephyr-2.0.0.bin -m zephyr

uhu package version 2.0.0

uhu package archive --output build/zephyr-2.0.0.pkg
```

**Logs and console output**

when I am running `uhu package add build/zephyr-2.0.0.bin -m zephyr`, I get the following error.
```
Error: Object duplicate.
```
And `uhu package archive --output build/zephyr-2.0.0.pkg` shows error too.
```
Traceback (most recent call last):
  File "/home/ihid/.local/bin/uhu", line 8, in <module>
    sys.exit(cli())
  File "/home/ihid/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ihid/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ihid/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ihid/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ihid/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ihid/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/cli/package.py", line 146, in archive_command
    dump_package_archive(package, output, force)
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/utils.py", line 55, in dump_package_archive
    metadata = package.to_metadata()
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/package.py", line 34, in to_metadata
    metadata.update(self.objects.to_metadata(callback))
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/objects.py", line 137, in to_metadata
    objects = [[obj.to_metadata(callback) for obj in set_]
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/objects.py", line 137, in <listcomp>
    objects = [[obj.to_metadata(callback) for obj in set_]
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/objects.py", line 137, in <listcomp>
    objects = [[obj.to_metadata(callback) for obj in set_]
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/_object.py", line 91, in to_metadata
    self.load(callback)
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/_object.py", line 140, in load
    for chunk in self:
  File "/home/ihid/.local/lib/python3.8/site-packages/uhu/core/_object.py", line 180, in __iter__
    with open(self.filename, 'br') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'build/zephyr-2.0.0.hex'
```

I would like to know why these two errors occurred and how I can fix them, thank you in advance for your help!

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.11.4
 - Commit SHA or Version used 4ca7942411f70f0caee6cd872ab14200f88b221b

**Comment by IHIDCHAOS** [comment]
Solved. Use `uhu cleanup` to clean old builds.
