### ISSUE TITLE
GUI configuration system (ninja menuconfig) exists with an error when the windows key is pressed

### ISSUE THREAD

**Issue by thedjnK** [zephyrproject-rtos/zephyr#33212]
**Describe the bug**
Configure a project for any board, run `ninja menuconfig` and press the windows key, it exits out with an error when it should handle it gracefully and ignore the input

**Expected behavior**
For it to not cause an exception

**Impact**
Annoyance

**Logs and console output**
```
Loaded configuration '<DIR>/app/build/zephyr/.config'
Traceback (most recent call last):
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 3278, in <module>
    _main()
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 663, in _main
    menuconfig(standard_kconfig(__doc__))
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 732, in menuconfig
    print(curses.wrapper(_menuconfig))
  File "C:\Python38\lib\curses\__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 872, in _menuconfig
    _change_node(sel_node)
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 1584, in _change_node
    s = _input_dialog(
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 1741, in _input_dialog
    _draw_input_dialog(win, title, info_lines, s, i, hscroll)
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 1791, in _draw_input_dialog
    _safe_addstr(win, 2, 2, visible_s + " "*(edit_width - len(visible_s)),
  File "<DIR>/zephyr/scripts/kconfig/menuconfig.py", line 3218, in _safe_addstr
    win.addnstr(y, x, s, maxlen, attr)
ValueError: embedded null character
Batch file failed at line 3 with errorcode 1
FAILED: CMakeFiles/menuconfig
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: N/A
 - Commit SHA: 4ce908a2342494c19df09f347ce79ab81b415185

**Comment by tejlmand** [comment]
@thedjnK fixed here: #33347
