### ISSUE TITLE
DOC BUILD FAIL

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#34068]
**Describe the bug**
LOG1:
```
E:zephyr\doc\_build\rst\doc\reference\bluetooth\gatt.rst:112: WARNING: Error in declarator
If declarator-id with parameters (e.g., 'void f(int arg)'):
  Invalid C declaration: Expected identifier in nested name. [error at 14]
    ATOMIC_DEFINE (flags, BT_GATT_SUBSCRIBE_NUM_FLAGS)
    --------------^
If parenthesis in noptr-declarator (e.g., 'void (*f(int arg))(double)'):
  Error in declarator or parameters
  Invalid C declaration: Expecting "(" in parameters. [error at 20]
    ATOMIC_DEFINE (flags, BT_GATT_SUBSCRIBE_NUM_FLAGS)
    --------------------^
```
FILE: zephyr\include\bluetooth\gatt.h
```
/** @brief GATT Subscribe parameters */
struct bt_gatt_subscribe_params {
	/** Notification value callback */
	bt_gatt_notify_func_t notify;
	/** Subscribe CCC write request response callback */
	bt_gatt_write_func_t write;
	/** Subscribe value handle */
	uint16_t value_handle;
	/** Subscribe CCC handle */
	uint16_t ccc_handle;
#if defined(CONFIG_BT_GATT_AUTO_DISCOVER_CCC)
	/** Subscribe End handle (for automatic discovery) */
	uint16_t end_handle;
	/** Discover parameters used when ccc_handle = 0 */
	struct bt_gatt_discover_params *disc_params;
#endif /* CONFIG_BT_GATT_AUTO_DISCOVER_CCC */
	/** Subscribe value */
	uint16_t value;
	/** Subscription flags */
	ATOMIC_DEFINE(flags, BT_GATT_SUBSCRIBE_NUM_FLAGS); -------------------------Here

	sys_snode_t node;
};
```

LOG2:
```
# Sphinx version: 3.2.1
# Python version: 3.9.0 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  0%] index
#   writing output... [  0%] reference/devicetree/bindings
#   writing output... [  0%] reference/devicetree/bindings/sensor/we,wsen-itds
#   writing output... [  1%] reference/devicetree/index
#   writing output... [  1%] releases/index
#   writing output... [  1%] releases/release-notes-2.5
# Loaded extensions:
#   sphinx.ext.mathjax (3.2.1) from c:\python39\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\python39\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\python39\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from c:\python39\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from c:\python39\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\python39\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\python39\lib\site-packages\alabaster\__init__.py
#   breathe (4.23.0) from c:\python39\lib\site-packages\breathe\__init__.py
#   sphinx.ext.todo (3.2.1) from c:\python39\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.extlinks (3.2.1) from c:\python39\lib\site-packages\sphinx\ext\extlinks.py
#   sphinx.ext.autodoc.type_comment (3.2.1) from c:\python39\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc (3.2.1) from c:\python39\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   zephyr.application (1.0) from E:\work\\zephyr\doc\_extensions\zephyr\application.py
#   zephyr.html_redirects (unknown version) from E:\work\\zephyr\doc\_extensions\zephyr\html_redirects.py
#   only.eager_only (unknown version) from E:\work\zephyr\doc\_extensions\only\eager_only.py
#   zephyr.dtcompatible-role (unknown version) from E:\work\zephyr\doc\_extensions\zephyr\dtcompatible-role.py
#   zephyr.link-roles (unknown version) from E:\work\zephyr\doc\_extensions\zephyr\link-roles.py
#   sphinx_tabs.tabs (unknown version) from c:\python39\lib\site-packages\sphinx_tabs\tabs.py
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\python39\lib\site-packages\sphinx\application.py", line 348, in build
    self.builder.build_update()
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 297, in build_update
    self.build(to_build,
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 542, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "c:\python39\lib\site-packages\sphinx\environment\__init__.py", line 539, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "c:\python39\lib\site-packages\sphinx\environment\__init__.py", line 585, in apply_post_transforms
    transformer.apply_transforms()
  File "c:\python39\lib\site-packages\sphinx\transforms\__init__.py", line 87, in apply_transforms
    super().apply_transforms()
  File "c:\python39\lib\site-packages\docutils\transforms\__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "c:\python39\lib\site-packages\sphinx\transforms\post_transforms\__init__.py", line 44, in apply
    self.run(**kwargs)
  File "c:\python39\lib\site-packages\sphinx\transforms\post_transforms\__init__.py", line 91, in run
    newnode = self.resolve_anyref(refdoc, node, contnode)
  File "c:\python39\lib\site-packages\sphinx\transforms\post_transforms\__init__.py", line 122, in resolve_anyref
    results.extend(domain.resolve_any_xref(self.env, refdoc, self.app.builder,
  File "c:\python39\lib\site-packages\sphinx\domains\c.py", line 3751, in resolve_any_xref
    return [('c:' + self.role_for_objtype(objtype), retnode)]
TypeError: can only concatenate str (not "NoneType") to str
```

Environment (please complete the following information):

Windows(Chinese)

**Comment by gmarull** [comment]
`ATOMIC_DEFINE(flags, BT_GATT_SUBSCRIBE_NUM_FLAGS);` is a known issue, and it is actually filtered out, has no relation with the reported problem. Looks like you are running out of date dependencies, make sure to run first `pip install -U scripts/requirements-doc.txt`. If the problem persists, you may try to set `SPHINXOPTS=` to see if default parallelization is the culprit.

**Comment by hongshui3000** [comment]
@gmarull 
Thanks
It can work after updating the version.

**Comment by hongshui3000** [comment]
This issue has been repeated with another issue   close it

**Comment by hongshui3000** [comment]
This issue has been repeated with another issue   close it

**Comment by hongshui3000** [comment]
This issue has been repeated with another issue   close it
