### ISSUE TITLE
jlink runner fails on M1 macs

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#34796]
**Describe the bug**

The new pylink library that jlink.py depends on doesn't work on M1 macs with x86 JLink tools.

**To Reproduce**

```
west build -b nrf52dk_nrf52832 -s samples/hello_world
west debug
```

**Expected behavior**

Works

**Impact**

Showstopper on that platform

**Logs and console output**

```
-- west debug: rebuilding
ninja: no work to do.
-- west debug: using runner jlink
Traceback (most recent call last):
  File "/Users/mbolivar/.virtualenvs/west-0.11/bin/west", line 8, in <module>
    sys.exit(main())
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/west/app/main.py", line 779, in main
    app.run(argv or sys.argv[1:])
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/west/app/main.py", line 338, in run_command
    self.run_extension(args.command, argv)
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/west/app/main.py", line 408, in run_extension
    command.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/west/commands.py", line 132, in run
    self.do_run(args, unknown)
  File "/Users/mbolivar/zephyrproject/zephyr/scripts/west_commands/debug.py", line 34, in do_run
    do_run_common(self, my_args, runner_args)
  File "/Users/mbolivar/zephyrproject/zephyr/scripts/west_commands/run_common.py", line 228, in do_run_common
    runner.run(command_name)
  File "/Users/mbolivar/zephyrproject/zephyr/scripts/west_commands/runners/core.py", line 509, in run
    self.do_run(command, **kwargs)
  File "/Users/mbolivar/zephyrproject/zephyr/scripts/west_commands/runners/jlink.py", line 191, in do_run
    self.logger.info(f'JLink version: {self.jlink_version_str}')
  File "/Users/mbolivar/zephyrproject/zephyr/scripts/west_commands/runners/jlink.py", line 166, in jlink_version_str
    major, minor, rev = self.jlink_version
  File "/Users/mbolivar/zephyrproject/zephyr/scripts/west_commands/runners/jlink.py", line 150, in jlink_version
    lib = Library(dllpath=os.fspath(Path(self.commander).parent /
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/pylink/library.py", line 259, in __init__
    self.load(dllpath)
  File "/Users/mbolivar/.virtualenvs/west-0.11/lib/python3.8/site-packages/pylink/library.py", line 353, in load
    self._lib = ctypes.cdll.LoadLibrary(tf.name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/var/folders/hh/58zc388x0_z1d4pg4s6_7vbw0000gn/T/tmpvzpcq9na.dylib, 6): no suitable image found.  Did find:
	/var/folders/hh/58zc388x0_z1d4pg4s6_7vbw0000gn/T/tmpvzpcq9na.dylib: mach-o, but wrong architecture
	/private/var/folders/hh/58zc388x0_z1d4pg4s6_7vbw0000gn/T/tmpvzpcq9na.dylib: mach-o, but wrong architecture
```

**Environment (please complete the following information):**
 - OS: macOS
 - Toolchain: GNU Arm Embedded
 - Commit SHA or Version used: 069c18d3ad

**Comment by mbolivar-nordic** [comment]
@carlescufi pointed out that https://www.segger.com/downloads/jlink/ contains builds for M1 macs. I'm going to close this as invalid.
