### ISSUE TITLE
AssertionError: zephyr/tests/kernel/common test case is failing with gcc-11 (Yocto)

### ISSUE THREAD

**Issue by saininav** [zephyrproject-rtos/zephyr#35707]
I am building stable zephyr v2.5.0 with Yocto toolchain using [meta-zephyr](http://git.yoctoproject.org/cgit/cgit.cgi/meta-zephyr) layer. 

GCC : 11.1.1
Python: 3.9.5
Board: up_squared

No issue observed with GCC 10.2.

Observed that few other [kernel testcases](https://github.com/zephyrproject-rtos/zephyr/tree/zephyr-v2.5.0/tests/kernel) are also failing with same error:
zephyr/tests/kernel/common
zephyr/tests/kernel/poll
zephyr/tests/kernel/queue
zephyr/tests/kernel/device

Error log:
```


| FAILED: zephyr/kobject_hash.gperf
| cd /data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/build/zephyr && /data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/recipe-sysroot-native/usr/bin/python3-native/python3 /data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/git/scripts/gen_kobject_list.py --kernel /data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/build/zephyr/zephyr_prebuilt.elf --gperf-output kobject_hash.gperf --include /data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/build/zephyr/misc/generated/struct_tags.json
| Traceback (most recent call last):
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/git/scripts/gen_kobject_list.py", line 1038, in <module>
|     main()
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/git/scripts/gen_kobject_list.py", line 1005, in main
|     objs = find_kobjects(elf, syms)
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/git/scripts/gen_kobject_list.py", line 525, in find_kobjects
|     for CU in di.iter_CUs():
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 353, in _parse_CUs_iter
|     cu = self._cached_CU_at_offset(offset)
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 383, in _cached_CU_at_offset
|     cu = self._parse_CU_at_offset(offset)
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 417, in _parse_CU_at_offset
|     cu_structs = DWARFStructs(
|   File "/data/saininav/work/workspace/zephyr-workspace/poky/build-zephyr/tmp-newlib/work/corei7-64-yocto-elf/common/2.5.0+gitAUTOINC+fe7c2efca8_c3bd2094f9-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/elftools/dwarf/structs.py", line 92, in __init__
|     assert address_size == 8 or address_size == 4
| AssertionError

```

**Comment by nashif** [comment]
I doubt this is board specific. This is a new toolchain that is not supported, not tested, etc. Please use the Zephyr SDK or a toolchain that is well-tested, for example 10.2

**Comment by nashif** [comment]
oops, closed by mistake

**Comment by nashif** [comment]
I can reproduce this with fedora 34 and `export ZEPHYR_TOOLCHAIN_VARIANT=host`

**Comment by nashif** [comment]
@dcpleung  take a look at the syscall script thing, you might have an idea what is going on.

**Comment by dcpleung** [comment]
#35852 takes care of some issues but not all of them.

There is an issue with linker section.

Another one is about `popcountdi2` being undefined, where we are actually using GCC's builtin popcount function. So this need some investigation.

**Comment by dcpleung** [comment]
@saininav Could you try again with the latest main branch? The DWARF error should have been fixed.

**Comment by saininav** [comment]
> @saininav Could you try again with the latest main branch? The DWARF error should have been fixed.

Yes I can build with latest main. Thanks.

Would this fix, be backported to release branch 'v2.6-branch'  ?

**Comment by dcpleung** [comment]
Backporting via #37447 and #37448

**Comment by dcpleung** [comment]
Both backport PRs have been merged.

**Comment by dcpleung** [comment]
@saininav Could you confirm that the backport works for you in v2.6?

**Comment by saininav** [comment]
It works. Thanks for backporting fixes.

**Comment by vindicatorr** [comment]
I've got the latest `main` branch today as well as `Zephyr SDK 0.13.2`, however the issue also occurs for me with `arm-none-eabi-gcc (Arch Repository) 11.2.0` as well as the older `arm-zephyr-eabi-gcc (crosstool-NG 1.24.0.378_e011758) 10.3.0`

```
> Executing task: ninja -C ./build footprint <

ninja: Entering directory `./build'
[1/151] Preparing syscall dependency handling

[140/151] Linking C executable zephyr/zephyr_pre0.elf

[144/151] Linking C executable zephyr/zephyr_pre1.elf

[150/151] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       13076 B      1020 KB      1.25%
            SRAM:        4192 B       256 KB      1.60%
        IDT_LIST:          0 GB         2 KB      0.00%
[150/151] cd <pathTo>/<project>/build...<pathTo>/<project>/build -d 99 all -q
Traceback (most recent call last):
  File "<pathTo>/zephyr//scripts/footprint/size_report", line 803, in <module>
    main()
  File "<pathTo>/zephyr//scripts/footprint/size_report", line 779, in main
    do_simple_name_matching(elf, symbol_dict, processed)
  File "<pathTo>/zephyr//scripts/footprint/size_report", line 268, in do_simple_name_matching
    for compile_unit in dwarfinfo.iter_CUs():
  File "/usr/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 353, in _parse_CUs_iter
    cu = self._cached_CU_at_offset(offset)
  File "/usr/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 383, in _cached_CU_at_offset
    cu = self._parse_CU_at_offset(offset)
  File "/usr/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 417, in _parse_CU_at_offset
    cu_structs = DWARFStructs(
  File "/usr/lib/python3.9/site-packages/elftools/dwarf/structs.py", line 92, in __init__
    assert address_size == 8 or address_size == 4
AssertionError
FAILED: zephyr/cmake/reports/CMakeFiles/footprint <pathTo>/<project>/build/zephyr/cmake/reports/CMakeFiles/footprint 
cd <pathTo>/<project>/build && /usr/bin/python3.9 <pathTo>/zephyr//scripts/footprint/size_report -k <pathTo>/<project>/build/zephyr/zephyr.elf -z <pathTo>/zephyr/ -o <pathTo>/<project>/build -d 99 all -q
```
