### ISSUE TITLE
RISC-V machine timer time-keeping question

### ISSUE THREAD

**Issue by berendo** [zephyrproject-rtos/zephyr#37852]
**Is your enhancement proposal related to a problem? Please describe.**
This enhancement proposal is not related to an as-of-yet identified problem, but the outcome of a code perusal that leads to a question.

**Describe the solution you'd like**
In the RISC-V machine timer ISR handler there are a series of lines which gets the current time and also adjust the "last" time to the current time: https://github.com/zephyrproject-rtos/zephyr/blob/2e045a0ed6b1fa32688d1d163c74652dbed19bd8/drivers/timer/riscv_machine_timer.c#L64-L67
Specifically, the `last_count` update arithmetically simplifies to:
```
last_count += dticks * CYC_PER_TICK
        ▼
last_count = last_count + ((now - last_count) / CYC_PER_TICK) * CYC_PER_TICK
        ▼
last_count = last_count + (now - last_count)
        ▼
last_count = now
```
However, the original `last_count += dticks * CYC_PER_TICK;` expression is susceptible to integer division errors if `CYC_PER_TICK` does not divide the `now - last_count` quantity exactly and when that is multiplied again `CYC_PER_TICK`, an accumulated error can be introduced which affects further timer scheduling.

@andyross @nashif is there any reason why this expression cannot be simplified to `last_count = now;`?

**Describe alternatives you've considered**
Please see above.

**Additional context**
N/A

**Comment by berendo** [comment]
I think now I have a seemingly-reproducible issue related to this... On a 64-bit RISC-V system with the machine timer running at 100 MHz (e.g. `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=100000000`), boot the system and connect with `gdb`, then CTRL-C and wait at the `gdb` prompt for ~43 seconds (which is where a `uint32_t` count would be saturated at 100 MHz). Then `continue` at the `gdb` prompt. What's observed is a never-ending timer ISR loop on a very short interval:
```
...
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
idle (unused1=<error reading variable: value has been optimized out>, unused2=<error reading variable: value has been optimized out>, unused3=<error reading variable: value has been optimized out>) at /home/berend/scorpio-fw/zephyr/kernel/idle.c:101
101                             k_cpu_idle();
...wait ~42 seconds...
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x000001000104159a in z_spin_lock_set_owner (l=l@entry=0x10001180098 <lock>) at /home/berend/scorpio-fw/zephyr/kernel/thread.c:866
866             l->thread_cpu = _current_cpu->id | (uintptr_t)_current;
(gdb) bt
#0  0x000001000104159a in z_spin_lock_set_owner (l=l@entry=0x10001180098 <lock>) at /home/berend/scorpio-fw/zephyr/kernel/thread.c:866
#1  0x000001000101fc60 in k_spin_lock (l=0x10001180098 <lock>) at /home/berend/scorpio-fw/zephyr/include/spinlock.h:141
#2  sys_clock_set_timeout (ticks=1, idle=idle@entry=false) at /home/berend/scorpio-fw/zephyr/drivers/timer/riscv_machine_timer.c:111
#3  0x0000010001042f4c in z_add_timeout (to=0x100011827a8 <shell_transport_uart_timer>, fn=fn@entry=0x10001043636 <z_timer_expiration_handler>, timeout=...) at /home/berend/scorpio-fw/zephyr/kernel/timeout.c:134
#4  0x0000010001043688 in z_timer_expiration_handler (t=0x100011827a8 <shell_transport_uart_timer>) at /home/berend/scorpio-fw/zephyr/kernel/timer.c:57
#5  0x00000100010433e8 in sys_clock_announce (ticks=ticks@entry=4299) at /home/berend/scorpio-fw/zephyr/kernel/timeout.c:252
#6  0x000001000101fb42 in timer_isr (arg=<optimized out>) at /home/berend/scorpio-fw/zephyr/drivers/timer/riscv_machine_timer.c:79
#7  0x00000100010000c6 in on_irq_stack () at /home/berend/scorpio-fw/zephyr/arch/riscv/core/isr.S:730
Backtrace stopped: frame did not save the PC
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x0000010001042f42 in z_add_timeout (to=0x100011827a8 <shell_transport_uart_timer>, fn=fn@entry=0x10001043636 <z_timer_expiration_handler>, timeout=...) at /home/berend/scorpio-fw/zephyr/kernel/timeout.c:132
132                             if (next_time == 0 ||
(gdb) bt
#0  0x0000010001042f42 in z_add_timeout (to=0x100011827a8 <shell_transport_uart_timer>, fn=fn@entry=0x10001043636 <z_timer_expiration_handler>, timeout=...) at /home/berend/scorpio-fw/zephyr/kernel/timeout.c:132
#1  0x0000010001043688 in z_timer_expiration_handler (t=0x100011827a8 <shell_transport_uart_timer>) at /home/berend/scorpio-fw/zephyr/kernel/timer.c:57
#2  0x00000100010433e8 in sys_clock_announce (ticks=ticks@entry=4299) at /home/berend/scorpio-fw/zephyr/kernel/timeout.c:252
#3  0x000001000101fb42 in timer_isr (arg=<optimized out>) at /home/berend/scorpio-fw/zephyr/drivers/timer/riscv_machine_timer.c:79
#4  0x00000100010000c6 in on_irq_stack () at /home/berend/scorpio-fw/zephyr/arch/riscv/core/isr.S:730
Backtrace stopped: frame did not save the PC
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x0000010001042f9c in z_add_timeout (to=<optimized out>, fn=fn@entry=0x10001043636 <z_timer_expiration_handler>, timeout=...) at /home/berend/scorpio-fw/zephyr/include/spinlock.h:172
172             __ASSERT(z_spin_unlock_valid(l), "Not my spinlock %p", l);
(gdb) bt
#0  0x0000010001042f9c in z_add_timeout (to=<optimized out>, fn=fn@entry=0x10001043636 <z_timer_expiration_handler>, timeout=...) at /home/berend/scorpio-fw/zephyr/include/spinlock.h:172
#1  0x0000010001043688 in z_timer_expiration_handler (t=0x100011827a8 <shell_transport_uart_timer>) at /home/berend/scorpio-fw/zephyr/kernel/timer.c:57
#2  0x00000100010433e8 in sys_clock_announce (ticks=ticks@entry=34394) at /home/berend/scorpio-fw/zephyr/kernel/timeout.c:252
#3  0x000001000101fb42 in timer_isr (arg=<optimized out>) at /home/berend/scorpio-fw/zephyr/drivers/timer/riscv_machine_timer.c:79
#4  0x00000100010000c6 in on_irq_stack () at /home/berend/scorpio-fw/zephyr/arch/riscv/core/isr.S:730
Backtrace stopped: frame did not save the PC
(gdb) 
```
If I change the `last_count` update from the original `last_count += dticks * CYC_PER_TICK;` to `last_count = now;` the problem goes away and the system behaves as usual even after long breaks during which the machine timer keeps counting, but the firmware not running.

Obviously the above scenario can be considered merely a "debugging nuisance," but I think it corroborates the observation that `last_count = now;` is the safer way to update `last_count` and there may be other more difficult to observe side-effects of the current implementation. I suspect that _anytime_ the `last_count` is updated erroneously due to the integer division ends up "falling behind" the next true wakeup to be scheduled, there is a whole series of very short (single tick?) wake-ups programmed into `mtimecmp` which increment `last_count` one tick at a time...
