### ISSUE TITLE
test: run testcase failed on platform mps2_an521_ns

### ISSUE THREAD

**Issue by yingmingx** [zephyrproject-rtos/zephyr#39418]
**Describe the bug**
When I was developing testcase, I found run twister failed on mps2_an521_ns on many testcase. For example:
twister -p mps2_an521_ns -T tests/lib/newlib/thread_safety/

**To Reproduce**
1. cd zephyrproject/zephyr
2. twister -p mps2_an521_ns -T tests/lib/newlib/thread_safety/

**Expected behavior**
testcase passed or skiped on this platform.

**Impact**
when run twister -T, if will build error on many testcases.

**Logs and console output**
```
Including boilerplate (Zephyr base): /home/yingming/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/yingming/zephyrproject/zephyr/tests/lib/newlib/thread_safety
-- Zephyr version: 2.7.99 (/home/yingming/zephyrproject/zephyr), build: v2.7.99-459-ge86f271a4cda
-- Found Python3: /usr/bin/python3.6 (found suitable exact version "3.6.9") found components: Interpreter
-- Found west (found suitable version "0.11.0", minimum required is "0.7.1")
-- Board: mps2_an521_ns
-- Cache files will be written to: /home/yingming/.cache/zephyr
-- Using toolchain: zephyr 0.13.1 (/home/yingming/zephyr-sdk-0.13.1)
-- Found dtc: /home/yingming/zephyr-sdk-0.13.1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/yingming/zephyrproject/zephyr/boards/arm/mps2_an521/mps2_an521_ns.dts
-- Generated zephyr.dts: /home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/zephyr/include/generated/device_extern.h
-- Including generated dts.cmake file: /home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/zephyr/dts.cmake
Parsing /home/yingming/zephyrproject/zephyr/tests/lib/newlib/thread_safety/Kconfig
Loaded configuration '/home/yingming/zephyrproject/zephyr/boards/arm/mps2_an521/mps2_an521_ns_defconfig'
Merged configuration 'prj_userspace.conf'
Merged configuration '/home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/twister/testcase_extra.conf'
Configuration saved to '/home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/zephyr/.config'
Kconfig header saved to '/home/yingming/zephyrproject/zephyr/twister-out/mps2_an521_ns/tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace/zephyr/include/generated/autoconf.h'
/home/yingming/zephyr-sdk-0.13.1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- The ASM compiler identification is GNU
......
[ 92%] Built target bl2_elf
[ 93%] Generating ../bin/bl2.bin
[ 93%] Built target bl2_bin
[ 93%] Generating ../bin/bl2.hex
[ 93%] Built target bl2_hex
[ 93%] Built target bl2_binaries
[ 94%] Building C object bl2/ext/mcuboot/CMakeFiles/signing_layout_s.dir/signing_layout_s.o
[ 94%] Built target signing_layout_s
[ 94%] Building C object bl2/ext/mcuboot/CMakeFiles/signing_layout_ns.dir/signing_layout_ns.o
[ 94%] Built target signing_layout_ns
[ 95%] Generating tfm_s_signed.bin
Traceback (most recent call last):
  File "/home/yingming/zephyrproject/modules/tee/tfm/trusted-firmware-m/bl2/ext/mcuboot/scripts/wrapper/wrapper.py", line 21, in <module>
    import imgtool.main
  File "/home/yingming/zephyrproject/bootloader/mcuboot/scripts/imgtool/main.py", line 23, in <module>
    import imgtool.keys as keys
  File "/home/yingming/zephyrproject/bootloader/mcuboot/scripts/imgtool/keys/__init__.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
ModuleNotFoundError: No module named 'cryptography.hazmat.primitives.asymmetric.ed25519'
bl2/ext/mcuboot/CMakeFiles/tfm_s_signed_bin.dir/build.make:70: recipe for target 'bl2/ext/mcuboot/tfm_s_signed.bin' failed
make[5]: *** [bl2/ext/mcuboot/tfm_s_signed.bin] Error 1
CMakeFiles/Makefile2:2136: recipe for target 'bl2/ext/mcuboot/CMakeFiles/tfm_s_signed_bin.dir/all' failed
make[4]: *** [bl2/ext/mcuboot/CMakeFiles/tfm_s_signed_bin.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make[3]: *** [all] Error 2
modules/trusted-firmware-m/CMakeFiles/tfm.dir/build.make:88: recipe for target 'modules/trusted-firmware-m/tfm-prefix/src/tfm-stamp/tfm-build' failed
make[2]: *** [modules/trusted-firmware-m/tfm-prefix/src/tfm-stamp/tfm-build] Error 2
CMakeFiles/Makefile2:3900: recipe for target 'modules/trusted-firmware-m/CMakeFiles/tfm.dir/all' failed
make[1]: *** [modules/trusted-firmware-m/CMakeFiles/tfm.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

**Environment (please complete the following information):**
OS: ubuntu1~18.04
Toolchain zephyr-sdk-0.13.1
Commit id d66a745d648864115d9cfbb30db532face9ecd66

**Comment by yingmingx** [comment]
After I update all requirements, it build pass, so this issue can be closed.
