### ISSUE TITLE
Bluetooth: Submitting more GATT writes than available buffers blocks for 30s and then errors out

### ISSUE THREAD

**Issue by jsiverskog** [zephyrproject-rtos/zephyr#39624]
**Describe the bug**
If I after subscribing to a characteristic fire away too many `bt_gatt_write`'s, the thread will block for 30 seconds.

I have:
```
CONFIG_BT_CONN_TX_MAX=10
CONFIG_BT_L2CAP_TX_BUF_COUNT=10
CONFIG_BT_BUF_ACL_TX_COUNT=10
```

If I after subscribing do:
```
    LOG_INF("subscribed");
    for (int i = 0; i < (CONFIG_BT_CONN_TX_MAX - 1); ++i) {
        if (bt_gatt_write(ble_api_conn->conn, &wr_params) != 0)
            LOG_ERR("write failed");
    }
    LOG_INF("wrote");
```
Everything works as expected:
```
[00:00:06.715,942] <inf> main: subscribed
[00:00:06.716,094] <inf> main: wrote
```
But if I iterate 10 (or more) times, this happens:
```
[00:00:12.633,605] <inf> main: subscribed
[00:00:42.633,911] <err> main: write failed
[00:00:42.633,941] <inf> main: wrote
```

**To Reproduce**
1. Connect and subscribe to a GATT characteristic
2. Write at least `CONFIG_BT_CONN_TX_MAX` times

**Expected behavior**
Either having `bt_gatt_write` return an error, or get an error in the registered callback.

**Impact**
Annoyance - I keep track of the number of outstanding writes to avoid this.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain gcc-arm-none-eabi-10.3-2021.07
 - v2.7.0 (but i'm pretty sure this has been an issue for a long time)

**Comment by alwa-nordic** [comment]
# Reproducing
I can reproduce this without any subscriptions on `samples/bluetooth/central`:

`prj.conf`:
```
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_GATT_CLIENT=y
```

Add to `main.c`:
```c
#include <logging/log.h>
LOG_MODULE_REGISTER(central);

void write_a_lot_callback(struct bt_conn *conn, uint8_t err,
				     struct bt_gatt_write_params *params)
{
	LOG_INF("Write request completed with BT_ATT_ERR 0x%02x", err);
}

static void write_a_lot(struct bt_conn * conn, uint16_t attr_handle)
{
	static uint8_t data[] = { 0x00 };
	static struct bt_gatt_write_params write_op;
	write_op = (struct bt_gatt_write_params){
		.handle = attr_handle,
		.offset = 0,
		.data = &data,
		.length = sizeof(data),
		.func = write_a_lot_callback,
	};

	LOG_INF("Writing a lot");
    for (int i = 0; i < (CONFIG_BT_CONN_TX_MAX + 5); ++i) {
		int err = bt_gatt_write(conn, &write_op);
        if (err) {
			LOG_ERR("Write request failed (%d)", err);
		}
		else {
			LOG_INF("Write request succeeded");
		}
    }
	LOG_INF("Done writing a lot");
}
```

Use the function at end of `static void connected(struct bt_conn *conn, uint8_t err)`:
```c
// The handle value does not matter
write_a_lot(conn, 1234);
```

# Stack trace
BT RX thread gets stuck on a timeout while the rest is idle:

```
>>> info threads
  Id   Target Id                                     Frame 
  2    Thread 536875024 (idle 00 UNKNOWN PRIO 15)    arch_cpu_idle () at /home/alwa/zephyrproject/zephyr/arch/arm/core/aarch32/cpu_idle.S:110
  3    Thread 536872936 (logging PENDING PRIO 14)    arch_swap (key=0) at /home/alwa/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  4    Thread 536875392 (sysworkq PENDING PRIO 255)  arch_swap (key=0) at /home/alwa/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  5    Thread 536873120 (BT TX PENDING PRIO 247)     arch_swap (key=0) at /home/alwa/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  6    Thread 536874152 (BT RX pri PENDING PRIO 246) arch_swap (key=0) at /home/alwa/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
* 7    Thread 536874336 (BT RX RUNNING PRIO 248)     bt_att_req_alloc (timeout=...) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/att.c:3031
```
```
>>> bt
#0  bt_att_req_alloc (timeout=...) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/att.c:3031
#1  0x0001c92c in gatt_req_alloc (encode=0x1c701 <gatt_write_encode>, op=18 '\022', len=3, params=0x20001264 <write_op>, func=0x1c5cb <gatt_write_rsp>) at /home/alwa/zephyrproject/zephyr/include/sys/time_units.h:378
#2  gatt_req_send (conn=conn@entry=0x20000958 <acl_conns>, func=0x1c5cb <gatt_write_rsp>, params=0x20001264 <write_op>, encode=0x1c701 <gatt_write_encode>, op=18 '\022', len=3) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/gatt.c:2047
#3  0x0000b8d8 in bt_gatt_write (conn=conn@entry=0x20000958 <acl_conns>, params=params@entry=0x20001264 <write_op>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/gatt.c:4323
#4  0x000034bc in write_a_lot (conn=conn@entry=0x20000958 <acl_conns>, attr_handle=1234) at /home/alwa/zephyrproject/zephyr/samples/bluetooth/central/src/main.c:99
#5  0x0000367a in connected (conn=0x20000958 <acl_conns>, err=<optimized out>) at /home/alwa/zephyrproject/zephyr/samples/bluetooth/central/src/main.c:133
#6  0x00007c7a in notify_connected (conn=conn@entry=0x20000958 <acl_conns>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/conn.c:1274
#7  0x0001bfd6 in bt_conn_connected (conn=conn@entry=0x20000958 <acl_conns>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/conn.c:1198
#8  0x000066a2 in bt_hci_le_enh_conn_complete (evt=evt@entry=0x20003840 <recv_thread_stack+960>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/hci_core.c:1306
#9  0x0001bdca in enh_conn_complete (evt=0x20003840 <recv_thread_stack+960>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/hci_core.c:1350
#10 le_legacy_conn_complete (buf=<optimized out>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/hci_core.c:1350
#11 0x00006bf6 in hci_event (buf=0x20005248 <net_buf_hci_rx_pool>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/hci_core.c:2325
#12 bt_recv (buf=buf@entry=0x20005248 <net_buf_hci_rx_pool>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/host/hci_core.c:3386
#13 0x0000d6ca in recv_thread (p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/alwa/zephyrproject/zephyr/subsys/bluetooth/controller/hci/hci_driver.c:527
#14 0x0001aaa6 in z_thread_entry (entry=0xd61d <recv_thread>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/alwa/zephyrproject/zephyr/lib/os/thread_entry.c:36
#15 0x0001aaa6 in z_thread_entry (entry=0xd61d <recv_thread>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/alwa/zephyrproject/zephyr/lib/os/thread_entry.c:36
#16 0x0c431924 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

# Analysis
`bt_gatt_write` is called from a bt event listener (`struct bt_conn_cb::connected` in this case). The event listener executes on the BT RX thread. `bt_gatt_write()` involves a `bt_att_req_alloc(BT_ATT_TIMEOUT)` that will block waiting for a `req`. But the `req` will be made available in the same BT RX thread, in the event loop further up the stack, after `connected` has returned. Thus the thread soft deadlocks until timeout.

I believe the original intention of the code is that `bt_att_req_alloc` and transitvely `bt_gatt_write` should not be called on BT RX thread. However, our samples do just this, which implies that this is expected to work.

# Needed fixes
The doc for `bt_gatt_write` specifies it's async. We have to adhere and never block. I'll open a PR replacing BT_ATT_TIMEOUT with K_NO_WAIT.

Docs must make it clear that bt event listeners are running on the BT RX thread and must be treated as ISRs. Do only thread-safe minimal work. Best practice is to just signal application thread, e.g. by semaphore or queue. Blocking will delay bluetooth event handling. I'll open a enchancement proposal.

**Comment by jsiverskog** [comment]
> This issue has been marked as stale because it has been open (more than) 60 days with no activity. Remove the stale label or add a comment saying that you would like to have the label removed otherwise this issue will automatically be closed in 14 days. Note, that you can always re-open a closed issue at any time.

please remove the stale label
