### ISSUE TITLE
samples/net/echo_client :failed to send data

### ISSUE THREAD

**Issue by rrahulkx** [zephyrproject-rtos/zephyr#4190]
This testcase compilation failed the complete log is attached here.

This testcase is failure console report is pasted below.

```
found expected `Compared [0-9]+ bytes, all ok` in console `/qz30j-x86:default` at 2.13s
console output: ***** delaying boot 1000ms (per build configuration) *****
console output: ***** BOOTING ZEPHYR OS v1.9.99 (delayed boot 1000ms) *****
console output: shell> [echo-client] [INF] init_app: Run echo client
console output: [echo-client] [ERR] connect_tcp: ^[[0;31mCannot connect TCP (-60)^[[0m
console output: [echo-client] [ERR] start_tcp: ^[[0;31mCannot init IPv6 TCP client (-60)^[[0m
console output: [echo-client] [DBG] tcp_received: (0x00400220): Sent 602 bytes, received 74 bytes
console output: [echo-client] [DBG] compare_tcp_data: (0x00400220): Compared 74 bytes, all ok
console output: [echo-client] [DBG] tcp_received: (0x00400220): Sent 602 bytes, received 128 bytes
console output: [echo-client] [DBG] compare_tcp_data: (0x00400220): Compared 128 bytes, all ok
console output: [echo-client] [DBG] tcp_received: (0x00400220): Sent 602 bytes, received 128 bytes
console output: [echo-client] [DBG] compare_tcp_data: (0x00400220): Compared 128 bytes, all ok
eval pass: found expected `Compared [0-9]+ bytes, all ok` in console `z30j-x86:default` at 2.13s
eval pass trace: Traceback (most recent call last)
eval pass: found expected `Compared [0-9]+ bytes, all ok` in console `z30j-x86:default` at 2.13s
eval pass trace: Traceback (most recent call last):
eval pass trace:   File "/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/.git/fl/expecter.py", line 255, in run
eval pass trace:     r = f(*args)
eval pass trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/git/expecter.py", line 444, in console_rx_eval
eval pass trace:     {'target': target })
eval pass trace: pass_e: (u'found expected `Compared [0-9]+ bytes, all ok` in console `qz30j-x86:default` at 2.13s', {'target': <.tc.target_c object at 0x7f8460358d50>})
read console '0j-x86:<default>' @0 812B
eval failed: Didn't get at least 10 'all ok' messages (but 3)
eval failed trace: Traceback (most recent call last):
eval failed trace:   File "/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/git//tc.py", line 1514, in _decorated_fn
eval failed trace:     r = fn(*args, **kwargs)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/.git//tc.py", line 3048, in _method_run
eval failed trace:     return self.__method_trampoline_call(fname, fn, _type, targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/.git/tc.py", line 3004, in __method_trampoline_call
eval failed trace:     r = getattr(self, fname)(*targets)
eval failed trace:   File "qa.git/tests/net/tcp/test_tcp.py", line 54, in eval_10_client
eval failed trace:     "messages (but %d)" % (need, len(matches)))
eval failed trace: failed_e: Didn't get at least 10 'all ok' messages (but 3)
evaluation failed
clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run171002-1901-262-A4cly6/uzr7/outdir-uzr7-7w2s-qemu_x86' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:256
clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run171002-1901-262-A4cly6/uzr7/outdir-uzr7-uhgo-qemu_x86' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/3-3/ZEPHYR_GCC_VARIANT/zephyr/.git/_zephyr.py:256
clean passed
COMPLETION failed
```

[Compeltation_failure.txt](https://github.com/zephyrproject-rtos/zephyr/files/1358726/Compeltation_failure.txt)

**Comment by rrahulkx** [comment]
This is Duplication of following github
 https://github.com/zephyrproject-rtos/zephyr/issues/4216
closing this Issue .
