### ISSUE TITLE
impossible to run west flash. NoneType error

### ISSUE THREAD

**Issue by thomasnonis** [zephyrproject-rtos/zephyr#42269]
**Describe the bug**
When i run `west flash` I get the reported error.

OpenOCD is installed and is in PATH, if I run `openocd` in the command line it works (`Open On-Chip Debugger 0.11.0 (2021-11-18)`).

**To Reproduce**
To reproduce run `west flash` in the zephyr directory

**Expected behavior**
The program should be built

**Impact**
If this doesn't get solved, no work can be done.

**Logs and console output**
```
west flash
 -- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner openocd
Traceback (most recent call last): 
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\Scripts\west.exe\__main__.py", line 7, in <module>
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\west\app\main.py", line 781, in main       
    app.run(argv or sys.argv[1:])
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\west\app\main.py", line 106, in run        
    self.run_command(argv)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\west\app\main.py", line 338, in run_command
    self.run_extension(args.command, argv)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\west\app\main.py", line 410, in run_extension
    command.run(args, unknown, self.topdir, manifest=self.manifest)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\west\commands.py", line 140, in run
    self.do_run(args, unknown)
  File "C:\Users\Thomas\Documents\ProgettoES\zephyrproject\zephyr\scripts\west_commands\flash.py", line 29, in do_run
    do_run_common(self, my_args, runner_args)
  File "C:\Users\Thomas\Documents\ProgettoES\zephyrproject\zephyr\scripts/west_commands\run_common.py", line 228, in do_run_common
    runner.run(command_name)
  File "C:\Users\Thomas\Documents\ProgettoES\zephyrproject\zephyr\scripts/west_commands\runners\core.py", line 537, in run
    self.do_run(command, **kwargs)
  File "C:\Users\Thomas\Documents\ProgettoES\zephyrproject\zephyr\scripts/west_commands\runners\openocd.py", line 197, in do_run
    self.require(self.openocd_cmd[0])
  File "C:\Users\Thomas\Documents\ProgettoES\zephyrproject\zephyr\scripts/west_commands\runners\core.py", line 582, in require
    ret = shutil.which(program)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 1401, in which
    if os.path.dirname(cmd):
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 223, in dirname
    return split(p)[0]
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Environment**
 - Windows 10 21H2 19044.1466
 - Toolchain: GNU ARM Embedded

**Comment by thomasnonis** [comment]
I deleted the whole zephyrproject directory and re-downloaded everything. This did the trick.
