### ISSUE TITLE
acrn_ehl_crb:  twister failed to run tests/subsys/logging due to UnicodeEncodeError after switching to log v2

### ISSUE THREAD

**Issue by enjiamai** [zephyrproject-rtos/zephyr#42548]
**Describe the bug**
The twister failed to run several tests/subsys/logging test suites on acrn_ehl_crb platform, it will meet a python exception and the twister will stop.  After bisect, this issue started from this commit: 262cc55609b73ea61b5f999c6c6daaba20bc5240 logging: Deprecate v1, default to v2

 - What target platform are you using?  only happened on acrn_ehl_crb board.
 - What have you tried to diagnose or workaround this issue?  

**To Reproduce**
1. source zephyr-env.sh
2. (reserve the remotehw for ehlsku11)
3. Apply the patch attached in the "Additional context".
4. twister -p acrn_ehl_crb --device-testing --device-serial-pty="/opt/remotehw/acrn-test-pty.exp,ehlsku11" --west-flash="/opt/remotehw/remotehw-x86-acrn.sh,ehlsku11"  -T  tests/subsys/logging/log_core_additional

**Expected behavior**
The test of tests/subsys/logging can pass and see the log output.

**Impact**
Cannot use twister to run tests/subsys/logging testing. Twister will crash due to "UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffc' in position 3319: ordinal not in range(256)
"

**Logs and console output**
```
$ twister -p acrn_ehl_crb --device-testing --device-serial-pty="/opt/remotehw/acrn-test-pty.exp,ehlsku11" --west-flash="/opt/remotehw/remotehw-x86-acrn.sh,ehlsku11"  -T  tests/subsys/logging/log_core_additional
Renaming output directory to /home/emai/work/zephyrproject/zephyr/twister-out.52
INFO    - Zephyr version: v2.7.99-3289-g262cc55609b7
INFO    - JOBS: 8
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testcase list...
INFO    - 4 test scenarios (4 configurations) selected, 0 configurations discarded due to filters.

Device testing on:

| Platform     | ID   | Serial device   |
|--------------|------|-----------------|
| acrn_ehl_crb |      |                 |

INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 3501, in pipeline_mgr
    pb.process(pipeline, done_queue, task, lock, results)
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 2437, in process
    res = self.cmake()
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 2676, in cmake
    res = self.run_cmake(args)
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 2198, in run_cmake
    log.write(log_msg)
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffc' in position 3127: ordinal not in range(256)
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 3501, in pipeline_mgr
    pb.process(pipeline, done_queue, task, lock, results)
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 2437, in process
    res = self.cmake()
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 2676, in cmake
    res = self.run_cmake(args)
  File "/home/emai/work/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 2198, in run_cmake
    log.write(log_msg)
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffc' in position 3162: ordinal not in range(256)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.2
 - Commit SHA or Version used: 

**Additional context**
Base on our testing process, before running the acrn_ehl_crb, should apply this patch first:
```
diff --git a/scripts/pylib/twister/twisterlib.py b/scripts/pylib/twister/twisterlib.py
index 512b6f51ad..5687cfff31 100755
--- a/scripts/pylib/twister/twisterlib.py
+++ b/scripts/pylib/twister/twisterlib.py
@@ -663,7 +663,7 @@ class DeviceHandler(Handler):
             # Just because ser_fileno has data doesn't mean an entire line
             # is available yet.
             if serial_line:
-                sl = serial_line.decode('utf-8', 'ignore').lstrip()
+                sl = serial_line.decode('latin-1', 'ignore').lstrip()
                 logger.debug("DEVICE: {0}".format(sl.rstrip()))

                 log_out_fp.write(sl)
@@ -3574,7 +3574,7 @@ class TestSuite(DisablePyTestCollectionMixin):
         filtered_string = ""
         if os.path.exists(log_file):
             with open(log_file, "rb") as f:
-                log = f.read().decode("utf-8")
+                log = f.read().decode("latin-1")
                 filtered_string = ''.join(filter(lambda x: x in string.printable, log))

         return filtered_string
```

**Comment by carlescufi** [comment]
@nashif FYI

**Comment by nashif** [comment]
> Should we just apply it locally? this is only related this board.

you need to submit this change. Do not apply anything locally.

**Comment by enjiamai** [comment]
> > Should we just apply it locally? this is only related this board.
> 
> you need to submit this change. Do not apply anything locally.

Ok, @nashif , got it, thanks!

**Comment by enjiamai** [comment]
This is my bad. This is due to environment problem. Just export the LANG=xxx.utf-8 solve the problem. So close this.
