### ISSUE TITLE
6LoCAN samples fail due to null pointer dereference

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#42559]
**Describe the bug**
The two samples `samples/net/sockets/echo_server` and `samples/net/sockets/echo_client`) for demonstrating 6LoCAN both fail to initialise due to dereferencing a NULL pointer.

A Git bisect shows that this issue (or at least an issue very similar to this issue, the value of the pointer in question is not always NULL but it's never a valid reference to a CAN device) exists since commit 62580748e536d5ff14ecc290e114c034f1ccccfd. This commit is present in the following Zephyr release branches:
- v2.4-branch
- v2.5-branch
- v2.6-branch
- v2.7-branch
- v3.0-branch

As far as I can tell, 6LoCAN has not worked since Zephyr v2.3.0. Even with v2.3.0, I was unable to get the echo server/client working via 6LoCAN on the NXP `frdm_k64f`, but at least the sample booted without a usage fault. 

**To Reproduce**
1. `cd samples/net/sockets/echo_server/`
2. `mkdir build; cd build`
3. `cmake -DBOARD=frdm_k64f -DOVERLAY_CONFIG="overlay-6locan.conf" -DCONFIG_ETH_MCUX=n ..`
4. `make debug` and do the following to inspect the pointer:

```
(gdb) break net_can_add_rx_filter 
Breakpoint 1 at 0x1c7e8: file /home/brix/Projects/zephyrproject/zephyr/drivers/can/can_net.c, line 230.
(gdb) cont
Continuing.
Note: automatically using hardware breakpoints for read-only addresses.

Breakpoint 1, net_can_add_rx_filter (dev=0x1df28 <__device_net_can_1>, cb=0x198eb <canbus_dad_resp_cb>, cb_arg=0x2000c798 <z_main_stack+1944>, filter=0x2000c770 <z_main_stack+1904>)
    at /home/brix/Projects/zephyrproject/zephyr/drivers/can/can_net.c:230
230		return can_add_rx_filter(ctx->can_dev, cb, cb_arg, filter);
(gdb) list
225	static int net_can_add_rx_filter(const struct device *dev, can_rx_callback_t cb,
226					 void *cb_arg, const struct zcan_filter *filter)
227	{
228		struct net_can_context *ctx = dev->data;
229	
230		return can_add_rx_filter(ctx->can_dev, cb, cb_arg, filter);
231	}
232	
233	static void net_can_remove_rx_filter(const struct device *dev, int filter_id)
234	{
(gdb) print ctx->can_dev 
$1 = (const struct device *) 0x0 <zsock_getaddrinfo>
(gdb) bt
#0  net_can_add_rx_filter (dev=0x1df28 <__device_net_can_1>, cb=0x198eb <canbus_dad_resp_cb>, cb_arg=0x2000c798 <z_main_stack+1944>, filter=0x2000c770 <z_main_stack+1904>)
    at /home/brix/Projects/zephyrproject/zephyr/drivers/can/can_net.c:230
#1  0x00006ec8 in canbus_add_dad_resp_filter (dad_sem=0x2000c798 <z_main_stack+1944>, ll_addr=<synthetic pointer>, net_can_dev=0x1df28 <__device_net_can_1>)
    at /home/brix/Projects/zephyrproject/zephyr/subsys/net/l2/canbus/6locan.c:1606
#2  canbus_init_ll_addr (iface=0x2000201c <__net_if_net_can_1_0>) at /home/brix/Projects/zephyrproject/zephyr/subsys/net/l2/canbus/6locan.c:1668
#3  canbus_enable (iface=0x2000201c <__net_if_net_can_1_0>, state=<optimized out>) at /home/brix/Projects/zephyrproject/zephyr/subsys/net/l2/canbus/6locan.c:1835
#4  0x00009866 in net_if_up (iface=iface@entry=0x2000201c <__net_if_net_can_1_0>) at /home/brix/Projects/zephyrproject/zephyr/subsys/net/ip/net_if.c:4026
#5  0x00009ae8 in net_if_post_init () at /home/brix/Projects/zephyrproject/zephyr/subsys/net/ip/net_if.c:4377
#6  0x00019940 in init_rx_queues () at /home/brix/Projects/zephyrproject/zephyr/subsys/net/ip/net_core.c:185
#7  net_init (unused=<optimized out>) at /home/brix/Projects/zephyrproject/zephyr/subsys/net/ip/net_core.c:494
#8  0x00014bd0 in z_sys_init_run_level (level=level@entry=2) at /home/brix/Projects/zephyrproject/zephyr/kernel/device.c:71
#9  0x00014e06 in bg_thread_main (unused1=<optimized out>, unused2=<optimized out>, unused3=<optimized out>) at /home/brix/Projects/zephyrproject/zephyr/kernel/init.c:180
#10 0x00016a34 in z_thread_entry (entry=0x14df9 <bg_thread_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/brix/Projects/zephyrproject/zephyr/lib/os/thread_entry.c:36
#11 0x00005bac in arch_switch_to_main_thread (main_thread=<optimized out>, stack_ptr=0x2000c820 <z_idle_stacks> "", _main=0x14df9 <bg_thread_main>)
    at /home/brix/Projects/zephyrproject/zephyr/arch/arm/core/aarch32/thread.c:557
#12 0x00000000 in ?? ()

```
**Expected behavior**
The `ctx->can_dev` pointer should point to a valid CAN device.

**Environment:**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain: Zephyr SDK 0.13.2
 - Commit: a775606ae95559daca40b65ba68509712fa5be65

**Additional context**
Up until December 2021, compilation of 6LoCAN was broken (see #40911) for a couple of months or more. I don't think this functionality has any users. Back then, I proposed removing it due to lack of users/maintenance (see #40722). If this functionality really has been broken since after v2.3.0, I am inclined to suggest removing it again.

**Comment by henrikbrixandersen** [comment]
@alexanderwachter Did you run any tests when submitting #40911 or did you just fix the compilation issue?
