### ISSUE TITLE
Custom driver offload socket creation failing

### ISSUE THREAD

**Issue by alissakruiniger** [zephyrproject-rtos/zephyr#46140]
I'm trying to set up a UDP socket connection for a driver I'm creating (Ublox SARA N310) that's similar to Ublox R4 (that makes use of socket offloading), but it fails.

Running GDB and stepping through the `socket()` function call eventually shows that in the function `net_context_get(family, type, proto)` has a function that fails with an error code of -134 (ENOTSUP). This is returned on a call to `net_offload_get()` (file:line `include/net/net_offload.h:142`).

Backtrace:
```
#0  net_context_get (family=family@entry=1, type=type@entry=SOCK_DGRAM, ip_proto=ip_proto@entry=17,
    context=context@entry=0x20002194 <z_main_stack+172>)
    at /home/hackerman/Zephyr/zephyrproject/zephyr/subsys/net/ip/net_context.c:336
#1  0x080023ba in zsock_socket_internal (family=1, type=2, proto=17)
    at /home/hackerman/Zephyr/zephyrproject/zephyr/subsys/net/lib/sockets/sockets.c:171
#2  0x0800244e in z_impl_zsock_socket (family=family@entry=1, type=type@entry=2, proto=proto@entry=17)
    at /home/hackerman/Zephyr/zephyrproject/zephyr/subsys/net/lib/sockets/sockets.c:225
#3  0x08000650 in zsock_socket (proto=17, type=2, family=1)
    at /home/hackerman/Zephyr/zephyrproject/zephyr/build/zephyr/include/generated/syscalls/socket.h:58
#4  socket (proto=17, type=2, family=1) at /home/hackerman/Zephyr/zephyrproject/zephyr/include/net/socket.h:652
#5  main () at /home/hackerman/Zephyr/zephyrproject/zephyr/samples/drivers/ublox_sara_n310/src/main.c:67
```
Error:
```
[00:00:19.647,000] <err> modem_ublox_sara_n310: CONFIG_NET_SOCKETS_OFFLOAD must be enabled for this driver
[00:00:19.647,000] <inf> main: Could not create socket. Return value: -1
[00:00:19.647,000] <inf> main: Connecting...
[00:00:19.647,000] <err> main: Bind failed with return value: -1 errno: 9
[00:00:19.647,000] <inf> main: Sending...
[00:00:19.647,000] <err> main: Send failed with return value: -1 errno: 9
[00:00:24.647,000] <inf> main: Receiving...
[00:00:24.647,000] <inf> main: Received: No data in buffer.
[00:00:26.647,000] <inf> main: Sending...
[00:00:26.647,000] <err> main: Send failed with return value: -1 errno: 9
```

**Comment by rlubos** [comment]
I'm afraid I can't help if you don't share any details on how is your offloaded socket implementation written (specifically how it's registered in the system). From the gdb output it's clear tha the native socket implementation is called.
