### ISSUE TITLE
`check_compliance.py` crash on Ubuntu 22.04

### ISSUE THREAD

**Issue by hx-bora** [zephyrproject-rtos/zephyr#47114]
## Describe the bug

Check compliance (`scripts/ci/check_compliance.py`) crashes on Ubuntu 22.04, probably due to some changes in recent version of Junitparser.

Here is the error:
`````
Running checkpatch       tests in /zephyrproject/zephyr ...
Running Kconfig          tests in None ...
Python exception in `/zephyrproject/zephyr/./scripts/ci/check_compliance.py`:

```
Traceback (most recent call last):
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 1131, in main
    n_fails = _main(args)
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 1082, in _main
    test.run()
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 229, in run
    kconf = self.parse_kconfig()
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 279, in parse_kconfig
    self.skip("Not a Zephyr tree (ZEPHYR_BASE unset)")
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 141, in skip
    self.case.result = Skipped(msg, "skipped")
  File "/usr/lib/python3/dist-packages/junitparser/junitparser.py", line 691, in result
    for entry in value:
TypeError: 'Skipped' object is not iterable

```
Traceback (most recent call last):
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 1158, in <module>
    main()
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 1131, in main
    n_fails = _main(args)
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 1082, in _main
    test.run()
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 229, in run
    kconf = self.parse_kconfig()
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 279, in parse_kconfig
    self.skip("Not a Zephyr tree (ZEPHYR_BASE unset)")
  File "/zephyrproject/zephyr/./scripts/ci/check_compliance.py", line 141, in skip
    self.case.result = Skipped(msg, "skipped")
  File "/usr/lib/python3/dist-packages/junitparser/junitparser.py", line 691, in result
    for entry in value:
TypeError: 'Skipped' object is not iterable
`````

The following horrible patch makes things work again:
```diff
diff --git a/scripts/ci/check_compliance.py b/scripts/ci/check_compliance.py
index 7ddb20044b..5185fc1778 100755
--- a/scripts/ci/check_compliance.py
+++ b/scripts/ci/check_compliance.py
@@ -138,7 +138,7 @@ class ComplianceTest:
         if self.case.result:
             msg += "\n\nFailures before skip: " + self.case.result._elem.text

-        self.case.result = Skipped(msg, "skipped")
+        self.case.result = [Skipped(msg, "skipped")]

         raise EndTest

@@ -149,11 +149,11 @@ class ComplianceTest:
         """
         if not self.case.result:
             # First reported failure
-            self.case.result = Failure(self.name + " issues", "failure")
-            self.case.result._elem.text = msg.rstrip()
+            self.case.result = [Failure(self.name + " issues", "failure")]
+            self.case.result[0]._elem.text = msg.rstrip()
         else:
             # If there are multiple Failures, concatenate their messages
-            self.case.result._elem.text += "\n\n" + msg.rstrip()
+            self.case.result[0]._elem.text += "\n\n" + msg.rstrip()

     def add_info(self, msg):
         """
@@ -1056,8 +1056,8 @@ def _main(args):

     for case in suite:
         if case.result:
-            if case.result.type == 'skipped':
-                logging.warning("Skipped %s, %s", case.name, case.result.message)
+            if case.result[0].type == 'skipped':
+                logging.warning("Skipped %s, %s", case.name, case.result[0].message)
             else:
                 failed_cases.append(case)
         else:
@@ -1071,14 +1071,14 @@ def _main(args):
         for case in failed_cases:
             # not clear why junitxml doesn't clearly expose the most
             # important part of its underlying etree.Element
-            errmsg = case.result._elem.text
+            errmsg = case.result[0]._elem.text
             logging.error("Test %s failed: %s", case.name,
-                          errmsg.strip() if errmsg else case.result.message)
+                          errmsg.strip() if errmsg else case.result[0].message)

             with open(f"{case.name}.txt", "w") as f:
                 docs = name2doc.get(case.name)
                 f.write(f"{docs}\n\n")
-                f.write(errmsg.strip() if errmsg else case.result.message)
+                f.write(errmsg.strip() if errmsg else case.result[0].message)

     print("\nComplete results in " + args.output)
     return n_fails
```

## To Reproduce

```shell
    ./scripts/ci/check_compliance.py
```

## Expected behavior

Compilation to succeed

## Impact

Script is unusable on Ubuntu 22.04

## Environment:

 - OS: Linux (Ubuntu 22.04)
 - Toolchain: Zephyr SDK 14.2
-  Commit SHA: 9a575e83debd4d7e6d20bdcf0d54d556f1e3e1a8 (main)

**Comment by stephanosio** [comment]
This problem does not have anything to do with Ubuntu 22.04, but with the version of junitparser package installed.

See https://github.com/zephyrproject-rtos/zephyr/commit/6d36386e139dd0c60e74842e2e6f5d4bd2026c4d

Please make sure that you install the Python packages according to the version specified in the requirements file:

https://github.com/zephyrproject-rtos/zephyr/blob/9a575e83debd4d7e6d20bdcf0d54d556f1e3e1a8/scripts/requirements-compliance.txt#L6
