### ISSUE TITLE
twister: frdm_k64f: twister process blocks after the flash error occurs

### ISSUE THREAD

**Issue by shaoanxli** [zephyrproject-rtos/zephyr#49086]
**Describe the bug**
twister process blocks after the flash error occurs, and the the problem is caused by this commit: 0ea346009f9d
There is always printing during the block: Waiting for device frdm_k64f to become available
And the twister process should not block after this error.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p frdm_k64f --hardware-map map.yml --device-testing -T tests/ -T samples/ -v
3. See error

**Expected behavior**
After the flash error occurs, the twister process still runs normally, and the flash error is displayed.

**Impact**
The test blcoks after the flash error occurs.

**Logs and console output (flash error)**
```
WARNING: runners: Argument --board-id is deprecated, use -i/--dev-id instead.
WARNING: runners.pyocd: hex file (None) does not exist; falling back on .bin (/home/ztest/zephyrproject/zephyr/twister-out/frdm_k64f/tests/arch/arm/arm_runtime_nmi/arch.interrupt.arm.nmi/zephyr/zephyr.bin). Consider enabling CONFIG_BUILD_OUTPUT_HEX.
0000505 C Device 02400201CCBF3E7D3141C3C5 not found [__main__]
[2mTraceback (most recent call last):
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/probe/cmsis_dap_probe.py", line 260, in open
    self._link.open()
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/utility/concurrency.py", line 29, in _locking
    return func(self, *args, **kwargs)
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 746, in open
    self._interface.open()
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/probe/pydapaccess/interface/pyusb_backend.py", line 80, in open
    raise DAPAccessIntf.DeviceError("Device %s not found" % self.serial_number)
pyocd.probe.pydapaccess.dap_access_api.DAPAccessIntf.DeviceError: Device 02400201CCBF3E7D3141C3C5 not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/__main__.py", line 161, in run
    status = cmd.invoke()
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/subcommands/load_cmd.py", line 96, in invoke
    with session:
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/core/session.py", line 391, in __enter__
    self.open()
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/core/session.py", line 525, in open
    self._probe.open()
  File "/home/ztest/.local/lib/python3.8/site-packages/pyocd/probe/cmsis_dap_probe.py", line 298, in open
    raise self._convert_exception(exc) from exc
pyocd.core.exceptions.ProbeError: Device 02400201CCBF3E7D3141C3C5 not found[0m
FATAL ERROR: command exited with status 1: pyocd flash -e sector -t k64f -u 02400201CCBF3E7D3141C3C5 /home/ztest/zephyrproject/zephyr/twister-out/frdm_k64f/tests/arch/arm/arm_runtime_nmi/arch.interrupt.arm.nmi/zephyr/zephyr.bin

```

**Environment :**
 - OS: Linux
 - Toolchain Zephyr SDK 0.14.1
 - Commit SHA or Version: 0ea346009f9d794e330ec74754a6d61e38b500ac

**Comment by enjiamai** [comment]
Hi @hakehuang , @PerMac , @chen-png , could you please help on reviewing the hotfix PR #49126  for this issue? This issue blocked our testing, thank you very much!
