### ISSUE TITLE
RPI Pico usb hangs up in interrupt handler for composite devices

### ISSUE THREAD

**Issue by lgehreke** [zephyrproject-rtos/zephyr#50983]
**Describe the bug**
I am using the rp2040 with the cdc_acm_composite sample.  When sending bytes
the first few bytes to the first acm port they will be echoed to the second acm port.
After a few more bytes the port will hang up.

**To Reproduce**
1. Build the cdc_acm_composite sample for the rp2040
2. Connect to ACM0 and ACM1 (or whatever they are called on your system)
3. Send bytes to ACM0
4. Observe the hangup

**Expected behavior**
All bytes should be echoed to ACM1

**Impact**
Composite devices are not usable

**Logs and console output**
It seems like there is some unhandled interrupt in the udc_rpi_isr which never gets cleared,
resulting in endless looping of the isr. gdb log:

```
Thread 1 received signal SIGINT, Interrupt.
0x100038bc in udc_rpi_isr (arg=<optimized out>) at /data/git/zephyr-workspace/zephyr/drivers/usb/device/usb_dc_rpi_pico.c:194
194     if (status & USB_INTS_DEV_CONN_DIS_BITS) {
(gdb) bt
#0  0x100038bc in udc_rpi_isr (arg=<optimized out>)
    at /data/git/zephyr-workspace/zephyr/drivers/usb/device/usb_dc_rpi_pico.c:194
#1  0x100034d4 in _isr_wrapper () at /data/git/zephyr-workspace/zephyr/arch/arm/core/aarch32/isr_wrapper.S:259
#2  <signal handler called>
#3  0x100033da in arch_irq_unlock (key=0)
    at /data/git/zephyr-workspace/zephyr/include/zephyr/arch/arm/aarch32/asm_inline_gcc.h:91
#4  arch_swap (key=key@entry=0) at /data/git/zephyr-workspace/zephyr/arch/arm/core/aarch32/swap.c:44
#5  0x10005224 in z_swap_irqlock (key=0) at /data/git/zephyr-workspace/zephyr/kernel/include/kswap.h:185
#6  z_swap (key=..., lock=0x20001684) at /data/git/zephyr-workspace/zephyr/kernel/include/kswap.h:196
#7  z_pend_curr (lock=lock@entry=0x20001684, key=..., wait_q=wait_q@entry=0x20000a28 <z_usb_work_q+120>,
    timeout=timeout@entry=...) at /data/git/zephyr-workspace/zephyr/kernel/sched.c:842
#8  0x100055e4 in z_sched_wait (lock=lock@entry=0x20001684, key=..., key@entry=...,
    wait_q=wait_q@entry=0x20000a28 <z_usb_work_q+120>, timeout=timeout@entry=..., data=data@entry=0x0)
    at /data/git/zephyr-workspace/zephyr/kernel/sched.c:1893
#9  0x10004d5c in work_queue_main (workq_ptr=0x200009b0 <z_usb_work_q>, p2=<optimized out>, p3=<optimized out>)
    at /data/git/zephyr-workspace/zephyr/kernel/work.c:660
#10 0x10005c0e in z_thread_entry (entry=0x10004d21 <work_queue_main>, p1=<optimized out>, p2=<optimized out>,
    p3=<optimized out>) at /data/git/zephyr-workspace/zephyr/lib/os/thread_entry.c:36
#11 0x10005c0e in z_thread_entry (entry=0x0, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>)
    at /data/git/zephyr-workspace/zephyr/lib/os/thread_entry.c:36
#12 0x10026040 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) b udc_rpi_isr
Breakpoint 1 at 0x10003858: file /data/git/zephyr-workspace/zephyr/drivers/usb/device/usb_dc_rpi_pico.c, line 179.
Note: automatically using hardware breakpoints for read-only addresses.
(gdb) c
Continuing.
target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x00000138 msp: 0x20041f00

Thread 1 hit Breakpoint 1, udc_rpi_isr (arg=0x0) at /data/git/zephyr-workspace/zephyr/drivers/usb/device/usb_dc_rpi_pico.c:179
179     uint32_t status = usb_hw->ints;
(gdb) n
183     if (status & USB_INTS_SETUP_REQ_BITS) {
(gdb) n
189     if (status & USB_INTS_BUFF_STATUS_BITS) {
(gdb) n
191         udc_rpi_handle_buff_status();
(gdb) n
194     if (status & USB_INTS_DEV_CONN_DIS_BITS) {
(gdb) n
209     if (status & USB_INTS_BUS_RESET_BITS) {
(gdb) n
230     if (status & USB_INTS_ERROR_DATA_SEQ_BITS) {
(gdb) n
236     if (status ^ handled) {
(gdb) s
237         LOG_ERR("unhandled IRQ: 0x%x", (uint)(status ^ handled));
```

```
*** Booting Zephyr OS build 1b26acca1e03  ***
[00:00:00.005,000] <inf> cdc_acm_composite: Wait for DTR
[00:00:04.317,000] <inf> usb_cdc_acm: Device disconnected
[00:00:04.317,000] <inf> usb_cdc_acm: Device disconnected
[00:00:04.393,000] <inf> usb_cdc_acm: Device disconnected
[00:00:04.394,000] <inf> usb_cdc_acm: Device disconnected
[00:00:04.478,000] <inf> usb_cdc_acm: Device configured
[00:00:04.478,000] <inf> usb_cdc_acm: Device configured
[00:00:28.834,000] <inf> cdc_acm_composite: DTR set, start test
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr-SDK 0.15.0, Zephyr 3.2

** Note **
Sometimes this bug also occurs when using a single acm device

**Comment by jfischer-no** [comment]
Should be fixed by #52145
