### ISSUE TITLE
[v2.7-branch] mgmt: mcumgr: img_mgmt: doing image list causes a device fault

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#51844]
**Describe the bug**
Using zephyr 2.7, the smp_svr sample, when configured for bluetooth, faults when an img_mgmt image list command is received. Backtrace shows:
```
#0  arch_system_halt (reason=reason@entry=0) at /tmp/aa/zephyr/kernel/fatal.c:30
#1  0x00038274 in k_sys_fatal_error_handler (reason=reason@entry=0, esf=esf@entry=0x20007090 <z_interrupt_stacks+1984>)
    at /tmp/aa/zephyr/kernel/fatal.c:44
#2  0x0003831e in z_fatal_error (reason=reason@entry=0, esf=esf@entry=0x20007090 <z_interrupt_stacks+1984>)
    at /tmp/aa/zephyr/kernel/fatal.c:127
#3  0x0001d9c8 in z_arm_fatal_error (reason=reason@entry=0, esf=esf@entry=0x20007090 <z_interrupt_stacks+1984>)
    at /tmp/aa/zephyr/arch/arm/core/aarch32/fatal.c:63
#4  0x0001e0c6 in z_arm_fault (msp=<optimized out>, psp=<optimized out>, exc_return=<optimized out>, callee_regs=<optimized out>)
    at /tmp/aa/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:1051
#5  0x0001e204 in z_arm_usage_fault () at /tmp/aa/zephyr/arch/arm/core/aarch32/cortex_m/fault_s.S:102
#6  <signal handler called>
#7  0x5df7fab4 in ?? ()
#8  0x00036e2c in boot_read_swap_state (fap=0x43120 <default_flash_map+48>, state=state@entry=0x20008ef8 <sys_work_q_stack+7720>)
    at /tmp/aa/bootloader/mcuboot/boot/bootutil/src/bootutil_public.c:263
#9  0x00040514 in boot_read_swap_state_by_id (flash_area_id=flash_area_id@entry=3, 
    state=state@entry=0x20008ef8 <sys_work_q_stack+7720>) at /tmp/aa/bootloader/mcuboot/boot/bootutil/src/bootutil_public.c:308
#10 0x00036ed2 in boot_swap_type_multi (image_index=image_index@entry=0)
    at /tmp/aa/bootloader/mcuboot/boot/bootutil/src/bootutil_public.c:426
#11 0x0004054a in boot_swap_type () at /tmp/aa/bootloader/mcuboot/boot/bootutil/src/bootutil_public.c:478
#12 0x0003eb3e in mcuboot_swap_type () at /tmp/aa/zephyr/subsys/dfu/boot/mcuboot.c:155
#13 0x00040bd4 in img_mgmt_impl_swap_type () at /tmp/aa/modules/lib/mcumgr/cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c:429
#14 0x00040ca8 in img_mgmt_state_flags (query_slot=query_slot@entry=0)
    at /tmp/aa/modules/lib/mcumgr/cmd/img_mgmt/src/img_mgmt_state.c:46
#15 0x0003796c in img_mgmt_state_read (ctxt=0x20008fec <sys_work_q_stack+7964>)
    at /tmp/aa/modules/lib/mcumgr/cmd/img_mgmt/src/img_mgmt_state.c:214
#16 0x0004106e in smp_handle_single_payload (handler_found=<synthetic pointer>, req_hdr=0x20008fcc <sys_work_q_stack+7932>, 
    cbuf=0x20008fec <sys_work_q_stack+7964>) at /tmp/aa/modules/lib/mcumgr/smp/src/smp.c:195
#17 smp_handle_single_req (handler_found=<synthetic pointer>, req_hdr=0x20008fcc <sys_work_q_stack+7932>, 
    streamer=0x20009044 <sys_work_q_stack+8052>) at /tmp/aa/modules/lib/mcumgr/smp/src/smp.c:245
#18 smp_process_request_packet (streamer=streamer@entry=0x20009044 <sys_work_q_stack+8052>, req=0x20009d9c <net_buf_pkt_pool>)
    at /tmp/aa/modules/lib/mcumgr/smp/src/smp.c:359
#19 0x00031da0 in zephyr_smp_process_packet (nb=<optimized out>, zst=0x20002ec8 <smp_bt_transport>)
    at /tmp/aa/zephyr/subsys/mgmt/mcumgr/smp.c:265
#20 zephyr_smp_handle_reqs (work=0x20002ec8 <smp_bt_transport>) at /tmp/aa/zephyr/subsys/mgmt/mcumgr/smp.c:281
#21 0x00038d64 in work_queue_main (workq_ptr=0x20001720 <k_sys_work_q>, p2=<optimized out>, p3=<optimized out>)
    at /tmp/aa/zephyr/kernel/work.c:651
#22 0x00039efe in z_thread_entry (entry=0x38ce1 <work_queue_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>)
    at /tmp/aa/zephyr/lib/os/thread_entry.c:36
#23 0xaaaaaaaa in ?? ()
```

**Expected behavior**
No crash to appear

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: 1f3121b6b2d151cd34d731174baeb1a007f1ff2c

**Comment by nordicjm** [comment]
False alarm, issue was caused by having secondary slot in external memory and Kconfig being disabled for it
