### ISSUE TITLE
Suspected sanitycheck breakage due to CONFIG_UART_ESP32

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#572]
Running `./scripts/sanitycheck --no-clean --enable-slow --inline-logs` on 634d3b46a95ff3e4b82ab27dbc94498c8ad95203 (current master HEAD), I get:

~~~
Could not build defconfig for qemu_x86_iamcu_tests_kernel_gen_isr_table_test_config-sanitycheck
make[1]: Entering directory '/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/tests/kernel/gen_isr_table'
make[2]: Entering directory '/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr'
make[3]: Entering directory '/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/sanity-out/qemu_x86_iamcu/tests/kernel/gen_isr_table/test'
  GEN     ./Makefile
scripts/kconfig/conf --silentoldconfig Kconfig
*
* Restart config...
*
*
* ESP32 UART driver
*
ESP32 UART driver (UART_ESP32) [N/y/?] (NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.

/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/scripts/kconfig/Makefile:49: recipe for target 'silentoldconfig' failed
make[5]: *** [silentoldconfig] Error 1
/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/Makefile:540: recipe for target 'silentoldconfig' failed
make[4]: *** [silentoldconfig] Error 2
make[3]: *** No rule to make target 'include/config/auto.conf', needed by 'include/generated/generated_dts_board.h'.
make[3]: Target 'dts' not remade because of errors.
make[3]: Leaving directory '/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/sanity-out/qemu_x86_iamcu/tests/kernel/gen_isr_table/test'
Makefile:178: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
make[2]: Target 'dts' not remade because of errors.
make[2]: Leaving directory '/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr'
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/Makefile.inc:126: recipe for target 'dts' failed
make[1]: *** [dts] Error 2
make[1]: Target 'config-sanitycheck' not remade because of errors.
make[1]: Leaving directory '/mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/tests/kernel/gen_isr_table'
Traceback (most recent call last):
  File "./scripts/sanitycheck", line 2071, in <module>
    main()
  File "./scripts/sanitycheck", line 1966, in main
    args.platform_limit, toolchain, args.extra_args, args.ccache)
  File "./scripts/sanitycheck", line 1387, in apply_filters
    raise SanityRuntimeError("Couldn't build some defconfigs")
__main__.SanityRuntimeError: Couldn't build some defconfigs
~~~

(tail of the output, error due to UART_ESP32 repeated multiple times)

@lpereira , please have a look.

**Comment by pfalcon** [comment]
Ok, I'm trying to always run sanitycheck with `--no-clean`, and that turns out to be culprit, it's not safe to keep sanity-out/ dir for a long time, over bunch of changes. Noted. Cleaning the dir fixed the issue.
