### ISSUE TITLE
Frdm_k64f samples/drivers/can/counter/ fails.

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#57654]
**Describe the bug**
This sample failed because of a timeout at the regex expectation.
The sample.yml defines the regex value as `Counter received: (.*)`
In the README file, we can read that the output should be like this:
```
Sample output
=============

.. code-block:: console

   Change LED filter ID: 0
   Finished init.
   Counter filter id: 4

   uart:~$ Counter received: 0
   Counter received: 1
   Counter received: 2
   Counter received: 3

```
It looks like it needs to have add-on external uart converter from frdm board to the testing host?
According to the handler.log file, there is only this part of sample output.
```
Change LED filter ID: 0
Finished init.
Counter filter id: 1
```
There is no  `Counter received: (.*)` value (at the main communication port).
This can be a reason for failing (timeout).

**To Reproduce**
`twister --device-testing --hardware-map <path_to>/map.yml -T ./samples/drivers/can/counter/ -v`

**Expected behavior**
Getting  `Counter received: (.*)` for regex expectation.

**Impact**
Annoyance.

**Logs and console output**
```
Renaming output directory to <path_to>/twister-out.10
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.3.0-3578-g1f43e126a841
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report <path_to>/twister-out/testplan.json

Device testing on:

| Platform   | ID                                               | Serial device                                                                                     |
|------------|--------------------------------------------------|---------------------------------------------------------------------------------------------------|
| frdm_k64f  | 02400b0132044e4500417009997b00316781000097969900 | /dev/serial/by-id/usb-ARM_DAPLink_CMSIS-DAP_02400b0132044e4500417009997b00316781000097969900-if01 |
| frdm_k64f  | 02400b0140214e45001b1018c89200349e11000097969900 | /dev/serial/by-id/usb-ARM_DAPLink_CMSIS-DAP_02400b0140214e45001b1018c89200349e11000097969900-if01 |

INFO    - JOBS: 8
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - 1/1 frdm_k64f                 samples/drivers/can/counter/sample.drivers.can.counter  FAILED Timeout (device 64.157s)
ERROR   - see: <path_to>/twister-out/frdm_k64f/samples/drivers/can/counter/sample.drivers.can.counter/handler.log

INFO    - 1 test scenarios (1 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
INFO    - 0 of 1 test configurations passed (0.00%), 1 failed, 0 errored, 0 skipped with 0 warnings in 69.52 seconds
INFO    - In total 1 test cases were executed, 0 skipped on 1 out of total 567 platforms (0.18%)
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board     | ID                                               |   Counter |
|-----------|--------------------------------------------------|-----------|
| frdm_k64f | 02400b0132044e4500417009997b00316781000097969900 |         1 |
| frdm_k64f | 02400b0140214e45001b1018c89200349e11000097969900 |         0 |
INFO    - Saving reports...
INFO    - Writing JSON report <path_to>/twister-out/twister.json
INFO    - Writing xunit report <path_to>/twister-out/twister.xml...
INFO    - Writing xunit report <path_to>/twister-out/twister_report.xml...
INFO    - -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
INFO    - The following issues were found (showing the top 10 items):
INFO    - 1) samples/drivers/can/counter/sample.drivers.can.counter on frdm_k64f failed (Timeout)
INFO    - 
INFO    - To rerun the tests, call twister using the following commandline:
INFO    - west twister -p <PLATFORM> -s <TEST ID>, for example:
INFO    - 
INFO    - west twister -p frdm_k64f -s samples/drivers/can/counter/sample.drivers.can.counter
INFO    - or with west:
INFO    - west build -p -b frdm_k64f -T samples/drivers/can/counter/sample.drivers.can.counter
INFO    - -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
INFO    - Run completed
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.0
 - West version: v0.13.1
 - Latest main: [84ba03a](https://github.com/zephyrproject-rtos/zephyr/commit/84ba03ae3fbbc71729a434d9fe888d739d545771)

**Comment by henrikbrixandersen** [comment]
Thank you for reporting this. I can reproduce this issue locally. A backtrace on the stuck `samples/drivers/can/counter` sample shows the following backtrace:

```
Program received signal SIGINT, Interrupt.
UART_GetStatusFlags (base=<optimized out>) at /home/hebad/Projects/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/uart/fsl_uart.c:676
676	    return status_flag;
(gdb) bt
#0  UART_GetStatusFlags (base=<optimized out>) at /home/hebad/Projects/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/uart/fsl_uart.c:676
#1  0x0000ce28 in uart_mcux_poll_out (dev=<optimized out>, c=<optimized out>) at /home/hebad/Projects/zephyrproject/zephyr/drivers/serial/uart_mcux.c:143
#2  0x00007bb6 in z_impl_uart_poll_out (dev=<optimized out>, out_char=116 't') at /home/hebad/Projects/zephyrproject/zephyr/include/zephyr/drivers/uart.h:583
#3  uart_poll_out (dev=<optimized out>, out_char=116 't') at /home/hebad/Projects/zephyrproject/zephyr/samples/drivers/can/counter/build/zephyr/include/generated/syscalls/uart.h:106
#4  console_out (c=116) at /home/hebad/Projects/zephyrproject/zephyr/drivers/console/uart_console.c:102
#5  0x00001498 in z_cbvprintf_impl (out=0xc469 <fputc>, ctx=ctx@entry=0x2 <_vector_table+2>, fp=<optimized out>, fp@entry=0x0 <_vector_table>, ap=..., ap@entry=..., flags=<optimized out>, flags@entry=0) at /home/hebad/Projects/zephyrproject/zephyr/lib/os/cbprintf_complete.c:1584
#6  0x00005f48 in cbvprintf (out=<optimized out>, ap=..., format=0x0 <_vector_table>, ctx=0x2 <_vector_table+2>) at /home/hebad/Projects/zephyrproject/zephyr/include/zephyr/sys/cbprintf.h:741
#7  printf (format=0xedb3 "State Change ISR\nstate: %s\nrx error count: %d\ntx error count: %d\n") at /home/hebad/Projects/zephyrproject/zephyr/lib/libc/minimal/source/stdout/fprintf.c:43
#8  0x000092cc in work_queue_main (workq_ptr=0x20000e90 <k_sys_work_q>, p2=<optimized out>, p3=<optimized out>) at /home/hebad/Projects/zephyrproject/zephyr/kernel/work.c:668
#9  0x0000a338 in z_thread_entry (entry=0x9249 <work_queue_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/hebad/Projects/zephyrproject/zephyr/lib/os/thread_entry.c:36
```

Reverting commit 3f0fc7fe6b8ff6fc7ca6cccbd40c4fb7349f5fe3 brings the back to life. This is related to the MCUX UART driver, not CAN. (cc: @dleach02).
