### ISSUE TITLE
Bluetooth, nRF51: ticker_success_assert during flash erase

### ISSUE THREAD

**Issue by ccollins476ad** [zephyrproject-rtos/zephyr#6229]
`BOARD=nrf51_pca10028`
`ZEPHYR_TOOLCHAIN_VARIANT=gccarmemb`
`GCCARMEMB_TOOLCHAIN_PATH=/usr/local/Caskroom/gcc-arm-embedded/6-2017-q2-update/gcc-arm-none-eabi-6-2017-q2-update`

Commit=`b55eb03e4085a53cc87c5a53b7dacf1df3536ae4` (+ diffs)
Application=`samples/bluetooth/peripheral`

I modified the peripheral sample application to erase a section of flash in its read handler for the heart rate sensor body sensor location characteristic (see diffs below).  When I use my phone to read this characteristic, I see the following message printed to the console:

```
[bt] [ERR] ticker_success_assert: assert: 'status == 0' failed
```

Here is some information collected at the time of the crash:
```
(gdb) whe
#0  _FaultDump (fault=3, esf=0x200034d8 <_interrupt_stack+1752>) at /Users/ccollins/repos/zephyr/arch/arm/core/fault.c:318
#1  _Fault (esf=0x200034d8 <_interrupt_stack+1752>) at /Users/ccollins/repos/zephyr/arch/arm/core/fault.c:365
#2  0x000011be in _stack_frame_endif () at /Users/ccollins/repos/zephyr/arch/arm/core/fault_s.S:110
#3  <signal handler called>
#4  ticker_success_assert (status=4, params=0x18187) at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/ll_sw/ctrl.c:4435
#5  0x0000a29a in ticker_job_op_cb (user_op=user_op@entry=0x2000133c <_ticker_user_ops+384>, status=status@entry=1) at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/ticker/ticker.c:480
#6  0x0000a7de in ticker_job_list_insert (insert_head=255 '\377', instance=0x20000aa0 <_instance>) at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/ticker/ticker.c:909
#7  ticker_job (param=0x20000aa0 <_instance>) at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/ticker/ticker.c:1120
#8  0x0000a16e in mayfly_run (callee_id=callee_id@entry=1 '\001') at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/util/mayfly.c:141
#9  0x00011f28 in swi4_nrf5_isr (arg=<optimized out>) at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/ll_sw/ll.c:131
#10 0x000012e4 in _idle_state_cleared () at /Users/ccollins/repos/zephyr/arch/arm/core/isr_wrapper.S:124
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) fr 5
#5  0x0000a29a in ticker_job_op_cb (user_op=user_op@entry=0x2000133c <_ticker_user_ops+384>, status=status@entry=1) at /Users/ccollins/repos/zephyr/subsys/bluetooth/controller/ticker/ticker.c:480
480                     user_op->fp_op_func(user_op->status, user_op->op_context);
(gdb) p user_op
$1 = (struct ticker_user_op *) 0x2000133c <_ticker_user_ops+384>
(gdb) p *user_op
$2 = {
  op = TICKER_USER_OP_TYPE_NONE,
  id = 0 '\000',
  params = {
    start = {
      ticks_at_start = 551708,
      ticks_first = 39,
      ticks_periodic = 0,
      remainder_periodic = 0,      lazy = 0,
      ticks_slot = 0,
      fp_timeout_func = 0xea01 <event_slave>,
      context = 0x20000d18 <_radio>
    },
    update = {
      ticks_drift_plus = 27420,
      ticks_drift_minus = 8,
      ticks_slot_plus = 39,
      ticks_slot_minus = 0,
      lazy = 0,
      force = 0 '\000'
    },
    slot_get = {
      ticker_id = 0x86b1c "",
      ticks_current = 0x27 <_vector_table+38>,
      ticks_to_expire = 0x0 <isr_tables_syms>
    }
  },
  status = 1,
  fp_op_func = 0xc901 <ticker_success_assert>,
  op_context = 0x1576 <_vprintk+318>
}
```

I tried setting `CONFIG_SOC_FLASH_NRF5_RADIO_SYNC=n` just to see what would happen, but it did not prevent the crash.

Below are the diffs I applied to my Zephyr repo:
```
diff --git a/samples/bluetooth/gatt/hrs.c b/samples/bluetooth/gatt/hrs.c
index 08ce43b43..6c07faadf 100644
--- a/samples/bluetooth/gatt/hrs.c
+++ b/samples/bluetooth/gatt/hrs.c
@@ -21,6 +21,8 @@
 #include <bluetooth/conn.h>
 #include <bluetooth/uuid.h>
 #include <bluetooth/gatt.h>
+#include <flash.h>
+#include <device.h>

 static struct bt_gatt_ccc_cfg hrmc_ccc_cfg[BT_GATT_CCC_MAX] = {};
 static u8_t simulate_hrm;
@@ -36,6 +38,24 @@ static void hrmc_ccc_cfg_changed(const struct bt_gatt_attr *attr,
 static ssize_t read_blsc(struct bt_conn *conn, const struct bt_gatt_attr *attr,
             void *buf, u16_t len, u16_t offset)
 {
+    struct device *flash_dev;
+    int rc;
+
+    flash_dev = device_get_binding(FLASH_DEV_NAME);
+
+    rc = flash_write_protection_set(flash_dev, false);
+    if (rc) {
+        return rc;
+    }
+
+    /* Erase the second image slot (104kB starting at 0x22000). */
+    rc = flash_erase(flash_dev, 0x22000, 104 * 1024);
+    if (rc) {
+        return rc;
+    }
+
+    rc = flash_write_protection_set(flash_dev, true);
+
    return bt_gatt_attr_read(conn, attr, buf, len, offset, &hrs_blsc,
                 sizeof(hrs_blsc));
 }
diff --git a/samples/bluetooth/peripheral/prj.conf b/samples/bluetooth/peripheral/prj.conf
index 7973a6144..89ac2f4c8 100644
--- a/samples/bluetooth/peripheral/prj.conf
+++ b/samples/bluetooth/peripheral/prj.conf
@@ -7,3 +7,4 @@ CONFIG_BT_ATT_PREPARE_COUNT=2
 CONFIG_BT_PRIVACY=y
 CONFIG_BT_DEVICE_NAME="Test peripheral"
 CONFIG_BT_DEVICE_APPEARANCE=833
+CONFIG_FLASH=y
```

I came across this issue while testing the mcumgr PR (https://github.com/zephyrproject-rtos/zephyr/pull/6068).  I used the peripheral sample application here as a minimal example that reproduces the crash.

**Comment by nvlsianpu** [comment]
cc @cvinayak  I  can't reproduce this using nRFConnect from my LG phone. Works fine.
