### ISSUE TITLE
tests: twister:  --prep-artifacts-for-testing --package-artifacts fails for all '/' platforms

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#69793]
**Describe the bug**

--prep-artifacts-for-testing --package-artifacts fails for all '/' platforms

**To Reproduce**
scripts/twister --prep-artifacts-for-testing --package-artifacts mimxrt1170_evk@A_mimxrt1176_cm7_twister_test_only.tar.gz -T samples/hello_world/ -p mimxrt1170_evk/mimxrt1176/cm7
Renaming output directory to /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out.1
INFO    - Using Ninja..
INFO    - Zephyr version: v3.6.0-389-ga07e7c65dab2
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/testplan.json
INFO    - JOBS: 16
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0, error:    0
INFO    - 1 test scenarios (1 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 errored, 0 skipped with 0 warnings in 8.01 seconds
INFO    - 0 test configurations executed on platforms, 1 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing JSON report /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/twister.json
INFO    - Writing xunit report /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/twister_report.xml...
Traceback (most recent call last):
  File "/home/shared/disk/zephyr_project/zephyr_test/zephyr/scripts/twister", line 214, in <module>
    ret = main(options)
          ^^^^^^^^^^^^^
  File "/home/shared/disk/zephyr_project/zephyr_test/zephyr/scripts/pylib/twister/twisterlib/twister_main.py", line 224, in main
    artifacts.package()
  File "/home/shared/disk/zephyr_project/zephyr_test/zephyr/scripts/pylib/twister/twisterlib/package.py", line 37, in package
    self.make_tarfile(self.options.package_artifacts, dirs)
  File "/home/shared/disk/zephyr_project/zephyr_test/zephyr/scripts/pylib/twister/twisterlib/package.py", line 21, in make_tarfile
    tar.add(d, arcname=os.path.join(root, f))
  File "/usr/lib/python3.11/tarfile.py", line 1986, in add
    tarinfo = self.gettarinfo(name, arcname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tarfile.py", line 1865, in gettarinfo
    statres = os.lstat(name)
              ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/mimxrt1170_evk/mimxrt1176/cm7/samples/hello_world/sample.basic.helloworld'

**Expected behavior**
PASS

**Logs and console output**

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used:  v3.6.0-389-ga07e7c65dab

**Comment by hakehuang** [comment]
@PerMac the HWv2 board naming breaks the --prep-artifacts-for-testing --package-artifacts settings
