### ISSUE TITLE
twister: pytest harness requires custom parameters even it does not exist

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#71817]
**Describe the bug**
The sample `samples/subsys/testsuite/pytest/shell/sample.pytest.shell` fails. 
This test uses `harness: pytest`. 
But the underlaying tests seem to pass just fine.

**To Reproduce**
1. connect `nrf52840dk/nrf52840`
2. run `scripts/twister -p nrf52840dk/nrf52840 -s sample.pytest.shell -v --inline-logs --device-testing --device-serial /dev/ttyACM0`
3. See error

**Expected behavior**
No reported failure

**Impact**
Failure in CI

**Logs and console output**
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kagi/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 1320, in pipeline_mgr
    pb.process(pipeline, done_queue, task, lock, results)
  File "/home/kagi/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 674, in process
    self.run()
  File "/home/kagi/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 1129, in run
    harness.pytest_run(instance.handler.get_test_timeout())
  File "/home/kagi/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/harness.py", line 303, in pytest_run
    cmd = self.generate_command()
  File "/home/kagi/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/harness.py", line 344, in generate_command
    self._generate_parameters_for_hardware(handler)
  File "/home/kagi/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/harness.py", line 385, in _generate_parameters_for_hardware
    for param in hardware.runner_params:
TypeError: 'NoneType' object is not iterable
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK 0.16.5
 - Commit SHA or Version used: a1dd9a5f6e562a11edc238e3af76dd64caddca83

**Additional context**
**The hw map was not used.**
Add checking the exist of the custom parameters does not trigger above traceback.

**Comment by gchwier** [comment]
Fix is provided by @katgiadla, ready to merge.
