### ISSUE TITLE
Lots of twister errors in CI that don't get reported as failures

### ISSUE THREAD

**Issue by arbrauns** [zephyrproject-rtos/zephyr#72807]
There are a lot of python exceptions being thrown in twister CI runs, but the run doesn't get marked as failed:

```
Process Process-17:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/__w/zephyr/zephyr/scripts/pylib/twister/twisterlib/runner.py", line [132](https://github.com/zephyrproject-rtos/zephyr/actions/runs/9094695276/job/24996411498#step:11:134)5, in pipeline_mgr
    pb.process(pipeline, done_queue, task, lock, results)
  File "/__w/zephyr/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 677, in process
    self.run()
  File "/__w/zephyr/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 1[134](https://github.com/zephyrproject-rtos/zephyr/actions/runs/9094695276/job/24996411498#step:11:136), in run
    instance.handler.handle(harness)
  File "/__w/zephyr/zephyr/scripts/pylib/twister/twisterlib/handlers.py", line 306, in handle
    with subprocess.Popen(command, stdout=subprocess.PIPE,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/__w/zephyr/zephyr/twister-out/unit_testing/tests/unit/winstream/utilities.winstream/zephyr/zephyr.exe'
```

Example: https://github.com/zephyrproject-rtos/zephyr/actions/runs/9094695276/job/24996411498#step:11:131

As far as I can tell, this kills the twister process and half the tests aren't even being run, yet no failure is reported in the GitHub action.

**Comment by PerMac** [comment]
I found the root cause of this. Will provide a fix soon

**Comment by nashif** [comment]
> the above link fixes "unit" type tests. Next PR will fix the exception handling so such errors are correctly reported

what next PR? where is it?

**Comment by PerMac** [comment]
WIP. Probably won't be able to push it today. The error with failing test is fixed. IMO failing unit tests were high priority. However, the fact that twister was not able to properly handle those issue is not that high, especially that this was already like this and the recent unit test errors just exposed this

**Comment by nashif** [comment]
ok, I will try and push something to address this

**Comment by PerMac** [comment]
I just opened a PR with proposition
