### ISSUE TITLE
pip install -r zephyr\scripts\requirements.txt broke: error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by exoism** [zephyrproject-rtos/zephyr#76067]
**Describe the bug**
Collecting lark<2.0,>=1.1.5 (from pyocd>=0.35.0->-r zephyr\scripts\requirements-run-test.txt (line 6))
  Using cached lark-1.1.9-py3-none-any.whl.metadata (1.9 kB)
Collecting libusb-package<2.0,>=1.0 (from pyocd>=0.35.0->-r zephyr\scripts\requirements-run-test.txt (line 6))
  Using cached libusb-package-1.0.26.1.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      cpython-mingw detected!
      Traceback (most recent call last):
        File "C:\msys64\ucrt64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\msys64\ucrt64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\msys64\ucrt64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Dranson\AppData\Local\Temp\pip-build-env-0ie5mkkk\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Dranson\AppData\Local\Temp\pip-build-env-0ie5mkkk\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\Dranson\AppData\Local\Temp\pip-build-env-0ie5mkkk\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
      AttributeError: 'NoneType' object has no attribute 'replace'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
<< Please describe the issue here >>
<< You may also want to update the automatically generated issue title above. >>

**Environment**
python 3.11.7
setuptools 71.0.2
rustc 1.79.0 for GNU windows

* Page: `develop/getting_started/index`
* Version: main
* SHA-1: 8b978ac1dca99b46bf32dafb6dcc3f93ef30274d

**Comment by marc-hb** [comment]
This looks like a problem with your MSYS installation, unrelated to Zephyr.
